/***************************************************************
This code was generated by Spiral 6.0 beta, www.spiral.net --
Copyright (c) 2005-2008, Carnegie Mellon University.
All rights reserved.
The code is distributed under the GNU General Public License (GPL)
(see http://www.gnu.org/copyleft/gpl.html)

THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
*AS IS* AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR
A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT
OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT
LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
(INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
******************************************************************/
#ifdef SSE_AVAILABLE
//#include <include/mm_malloc.h>
//#include <pmmintrin.h>
#include <emmintrin.h>
#include <xmmintrin.h>
#include <mmintrin.h>
#endif
#include "viterbi_spiral.h"

void init_FULL_SPIRAL() {
}

#ifdef SSE_AVAILABLE

void FULL_SPIRAL (int amount, int32_t  *Y, int32_t  *X, int32_t  *syms, unsigned char  *dec, int32_t  *Branchtab) {
int i9;
//    for(i9 = 0; i9 <= amount; i9++) {
    for(i9 = 0; i9 < amount; i9++) {
        int32_t a1002, a1006, a1010, a1014, a822, a828, a834
                , a840;
        int a820, a850;
        unsigned char s118, s125, s132, s139, s146, s153, s160
                , s167, s174, s181, s188, s195, s202, s209, s216
                , s223;
        int32_t  *a1001, *a1005, *a1009, *a1013, *a821, *a827, *a833
                , *a839, *b104;
        unsigned char  *a1021, *a1030, *a1039, *a1048, *a1057, *a1066, *a1075
                , *a1084, *a849, *a851, *a872, *a893, *a914, *a935, *a956
                , *a977, *a998;
        __m128i  *a1000, *a818, *a819, *a824, *a830, *a836, *a842
                , *a852, *a853, *a854, *a855, *a856, *a859, *a862, *a865
                , *a873, *a874, *a875, *a876, *a877, *a880, *a883, *a886
                , *a894, *a895, *a896, *a897, *a898, *a901, *a904, *a907
                , *a915, *a916, *a917, *a918, *a919, *a922, *a925, *a928
                , *a936, *a937, *a938, *a939, *a940, *a943, *a946, *a949
                , *a957, *a958, *a959, *a960, *a961, *a964, *a967, *a970
                , *a978, *a979, *a980, *a981, *a982, *a985, *a988, *a991
                , *a999;
        __m128i a1003, a1004, a1007, a1008, a1011, a1012, a1015
                , a1016, a1017, a1018, a1019, a1020, a1022, a1023, a1024
                , a1025, a1026, a1027, a1028, a1029, a1031, a1032, a1033
                , a1034, a1035, a1036, a1037, a1038, a1040, a1041, a1042
                , a1043, a1044, a1045, a1046, a1047, a1049, a1050, a1051
                , a1052, a1053, a1054, a1055, a1056, a1058, a1059, a1060
                , a1061, a1062, a1063, a1064, a1065, a1067, a1068, a1069
                , a1070, a1071, a1072, a1073, a1074, a1076, a1077, a1078
                , a1079, a1080, a1081, a1082, a1083, a823, a825, a826
                , a829, a831, a832, a835, a837, a838, a841, a843
                , a844, a845, a846, a847, a848, a857, a858, a860
                , a861, a863, a864, a866, a867, a868, a869, a870
                , a871, a878, a879, a881, a882, a884, a885, a887
                , a888, a889, a890, a891, a892, a899, a900, a902
                , a903, a905, a906, a908, a909, a910, a911, a912
                , a913, a920, a921, a923, a924, a926, a927, a929
                , a930, a931, a932, a933, a934, a941, a942, a944
                , a945, a947, a948, a950, a951, a952, a953, a954
                , a955, a962, a963, a965, a966, a968, a969, a971
                , a972, a973, a974, a975, a976, a983, a984, a986
                , a987, a989, a990, a992, a993, a994, a995, a996
                , a997, b105, b106, b107, b108, b109, b110, b111
                , b112, b113, b114, b115, b116, b117, b118, b119
                , b120, b121, b122, b123, b124, b125, b126, b127
                , b128, b129, b130, b131, b132, b133, b134, b135
                , b136, d37, d38, d39, d40, d41, d42, d43
                , d44, d45, d46, d47, d48, d49, d50, d51
                , d52, d53, d54, d55, d56, d57, d58, d59
                , d60, d61, d62, d63, d64, d65, d66, d67
                , d68, m100, m101, m102, m103, m104, m105, m106
                , m107, m108, m109, m110, m111, m112, m113, m114
                , m115, m116, m117, m118, m119, m120, m121, m122
                , m123, m124, m125, m126, m127, m128, m129, m130
                , m131, m132, m133, m134, m135, m136, m73, m74
                , m75, m76, m77, m78, m79, m80, m81, m82
                , m83, m84, m85, m86, m87, m88, m89, m90
                , m91, m92, m93, m94, m95, m96, m97, m98
                , m99, s114, s115, s116, s117, s119, s120, s121
                , s122, s123, s124, s126, s127, s128, s129, s130
                , s131, s133, s134, s135, s136, s137, s138, s140
                , s141, s142, s143, s144, s145, s147, s148, s149
                , s150, s151, s152, s154, s155, s156, s157, s158
                , s159, s161, s162, s163, s164, s165, s166, s168
                , s169, s170, s171, s172, s173, s175, s176, s177
                , s178, s179, s180, s182, s183, s184, s185, s186
                , s187, s189, s190, s191, s192, s193, s194, s196
                , s197, s198, s199, s200, s201, s203, s204, s205
                , s206, s207, s208, s210, s211, s212, s213, s214
                , s215, s217, s218, s219, s220, s221, s222, s224
                , s225, t39, t40, t41, t42, t43, t44, t45
                , t46, t47, t48, t49, t50, t51, t52, t53
                , t54, t55, t56, t57, t58, t59, t60, t61
                , t62, t63, t64, t65, t66, t67, t68, t69
                , t70;
        a818 = ((__m128i  *) X);
        s114 = *(a818);
        a819 = (a818 + 8);
        s115 = *(a819);
        a820 = (8 * i9);
        a821 = (syms + a820);
        a822 = *(a821);
        a823 = _mm_set1_epi32(a822);
        a824 = ((__m128i  *) Branchtab);
        a825 = *(a824);
        a826 = _mm_xor_si128(a823, a825);
        b104 = (a820 + syms);
        a827 = (b104 + 1);
        a828 = *(a827);
        a829 = _mm_set1_epi32(a828);
        a830 = (a824 + 8);
        a831 = *(a830);
        a832 = _mm_xor_si128(a829, a831);
        a833 = (b104 + 2);
        a834 = *(a833);
        a835 = _mm_set1_epi32(a834);
        a836 = (a824 + 16);
        a837 = *(a836);
        a838 = _mm_xor_si128(a835, a837);
        a839 = (b104 + 3);
        a840 = *(a839);
        a841 = _mm_set1_epi32(a840);
        a842 = (a824 + 24);
        a843 = *(a842);
        a844 = _mm_xor_si128(a841, a843);
        b105 = _mm_add_epi32(a826, a832);
        b106 = _mm_add_epi32(b105, a838);
        t39 = _mm_add_epi32(b106, a844);
        t40 = _mm_sub_epi32(_mm_set_epi32(1020, 1020, 1020, 1020), t39);
        m73 = _mm_add_epi32(s114, t39);
        m74 = _mm_add_epi32(s115, t40);
        m75 = _mm_add_epi32(s114, t40);
        m76 = _mm_add_epi32(s115, t39);
        d37 = _mm_cmpgt_epi32(m73, m74);
        d38 = _mm_cmpgt_epi32(m75, m76);
        a845 = _mm_andnot_si128(d37, m73);
        a846 = _mm_and_si128(d37, m74);
        s116 = _mm_or_si128(a845, a846);
        a847 = _mm_andnot_si128(d38, m75);
        a848 = _mm_and_si128(d38, m76);
        s117 = _mm_or_si128(a847, a848);
        s118 = _mm_movemask_epi8(_mm_packs_epi16(_mm_unpacklo_epi16(_mm_packs_epi16(d37,_mm_setzero_si128()),_mm_packs_epi16(d38,_mm_setzero_si128())),_mm_setzero_si128()));
        a849 = ((unsigned char  *) dec);
        a850 = (16 * i9);
        a851 = (a849 + a850);
        *(a851) = s118;
        s119 = _mm_unpacklo_epi32(s116, s117);
        s120 = _mm_unpackhi_epi32(s116, s117);
        a852 = ((__m128i  *) Y);
        *(a852) = s119;
        a853 = (a852 + 1);
        *(a853) = s120;
        a854 = (a818 + 1);
        s121 = *(a854);
        a855 = (a818 + 9);
        s122 = *(a855);
        a856 = (a824 + 1);
        a857 = *(a856);
        a858 = _mm_xor_si128(a823, a857);
        a859 = (a824 + 9);
        a860 = *(a859);
        a861 = _mm_xor_si128(a829, a860);
        a862 = (a824 + 17);
        a863 = *(a862);
        a864 = _mm_xor_si128(a835, a863);
        a865 = (a824 + 25);
        a866 = *(a865);
        a867 = _mm_xor_si128(a841, a866);
        b107 = _mm_add_epi32(a858, a861);
        b108 = _mm_add_epi32(b107, a864);
        t41 = _mm_add_epi32(b108, a867);
        t42 = _mm_sub_epi32(_mm_set_epi32(1020, 1020, 1020, 1020), t41);
        m77 = _mm_add_epi32(s121, t41);
        m78 = _mm_add_epi32(s122, t42);
        m79 = _mm_add_epi32(s121, t42);
        m80 = _mm_add_epi32(s122, t41);
        d39 = _mm_cmpgt_epi32(m77, m78);
        d40 = _mm_cmpgt_epi32(m79, m80);
        a868 = _mm_andnot_si128(d39, m77);
        a869 = _mm_and_si128(d39, m78);
        s123 = _mm_or_si128(a868, a869);
        a870 = _mm_andnot_si128(d40, m79);
        a871 = _mm_and_si128(d40, m80);
        s124 = _mm_or_si128(a870, a871);
        s125 = _mm_movemask_epi8(_mm_packs_epi16(_mm_unpacklo_epi16(_mm_packs_epi16(d39,_mm_setzero_si128()),_mm_packs_epi16(d40,_mm_setzero_si128())),_mm_setzero_si128()));
        a872 = (a851 + 1);
        *(a872) = s125;
        s126 = _mm_unpacklo_epi32(s123, s124);
        s127 = _mm_unpackhi_epi32(s123, s124);
        a873 = (a852 + 2);
        *(a873) = s126;
        a874 = (a852 + 3);
        *(a874) = s127;
        a875 = (a818 + 2);
        s128 = *(a875);
        a876 = (a818 + 10);
        s129 = *(a876);
        a877 = (a824 + 2);
        a878 = *(a877);
        a879 = _mm_xor_si128(a823, a878);
        a880 = (a824 + 10);
        a881 = *(a880);
        a882 = _mm_xor_si128(a829, a881);
        a883 = (a824 + 18);
        a884 = *(a883);
        a885 = _mm_xor_si128(a835, a884);
        a886 = (a824 + 26);
        a887 = *(a886);
        a888 = _mm_xor_si128(a841, a887);
        b109 = _mm_add_epi32(a879, a882);
        b110 = _mm_add_epi32(b109, a885);
        t43 = _mm_add_epi32(b110, a888);
        t44 = _mm_sub_epi32(_mm_set_epi32(1020, 1020, 1020, 1020), t43);
        m81 = _mm_add_epi32(s128, t43);
        m82 = _mm_add_epi32(s129, t44);
        m83 = _mm_add_epi32(s128, t44);
        m84 = _mm_add_epi32(s129, t43);
        d41 = _mm_cmpgt_epi32(m81, m82);
        d42 = _mm_cmpgt_epi32(m83, m84);
        a889 = _mm_andnot_si128(d41, m81);
        a890 = _mm_and_si128(d41, m82);
        s130 = _mm_or_si128(a889, a890);
        a891 = _mm_andnot_si128(d42, m83);
        a892 = _mm_and_si128(d42, m84);
        s131 = _mm_or_si128(a891, a892);
        s132 = _mm_movemask_epi8(_mm_packs_epi16(_mm_unpacklo_epi16(_mm_packs_epi16(d41,_mm_setzero_si128()),_mm_packs_epi16(d42,_mm_setzero_si128())),_mm_setzero_si128()));
        a893 = (a851 + 2);
        *(a893) = s132;
        s133 = _mm_unpacklo_epi32(s130, s131);
        s134 = _mm_unpackhi_epi32(s130, s131);
        a894 = (a852 + 4);
        *(a894) = s133;
        a895 = (a852 + 5);
        *(a895) = s134;
        a896 = (a818 + 3);
        s135 = *(a896);
        a897 = (a818 + 11);
        s136 = *(a897);
        a898 = (a824 + 3);
        a899 = *(a898);
        a900 = _mm_xor_si128(a823, a899);
        a901 = (a824 + 11);
        a902 = *(a901);
        a903 = _mm_xor_si128(a829, a902);
        a904 = (a824 + 19);
        a905 = *(a904);
        a906 = _mm_xor_si128(a835, a905);
        a907 = (a824 + 27);
        a908 = *(a907);
        a909 = _mm_xor_si128(a841, a908);
        b111 = _mm_add_epi32(a900, a903);
        b112 = _mm_add_epi32(b111, a906);
        t45 = _mm_add_epi32(b112, a909);
        t46 = _mm_sub_epi32(_mm_set_epi32(1020, 1020, 1020, 1020), t45);
        m85 = _mm_add_epi32(s135, t45);
        m86 = _mm_add_epi32(s136, t46);
        m87 = _mm_add_epi32(s135, t46);
        m88 = _mm_add_epi32(s136, t45);
        d43 = _mm_cmpgt_epi32(m85, m86);
        d44 = _mm_cmpgt_epi32(m87, m88);
        a910 = _mm_andnot_si128(d43, m85);
        a911 = _mm_and_si128(d43, m86);
        s137 = _mm_or_si128(a910, a911);
        a912 = _mm_andnot_si128(d44, m87);
        a913 = _mm_and_si128(d44, m88);
        s138 = _mm_or_si128(a912, a913);
        s139 = _mm_movemask_epi8(_mm_packs_epi16(_mm_unpacklo_epi16(_mm_packs_epi16(d43,_mm_setzero_si128()),_mm_packs_epi16(d44,_mm_setzero_si128())),_mm_setzero_si128()));
        a914 = (a851 + 3);
        *(a914) = s139;
        s140 = _mm_unpacklo_epi32(s137, s138);
        s141 = _mm_unpackhi_epi32(s137, s138);
        a915 = (a852 + 6);
        *(a915) = s140;
        a916 = (a852 + 7);
        *(a916) = s141;
        a917 = (a818 + 4);
        s142 = *(a917);
        a918 = (a818 + 12);
        s143 = *(a918);
        a919 = (a824 + 4);
        a920 = *(a919);
        a921 = _mm_xor_si128(a823, a920);
        a922 = (a824 + 12);
        a923 = *(a922);
        a924 = _mm_xor_si128(a829, a923);
        a925 = (a824 + 20);
        a926 = *(a925);
        a927 = _mm_xor_si128(a835, a926);
        a928 = (a824 + 28);
        a929 = *(a928);
        a930 = _mm_xor_si128(a841, a929);
        b113 = _mm_add_epi32(a921, a924);
        b114 = _mm_add_epi32(b113, a927);
        t47 = _mm_add_epi32(b114, a930);
        t48 = _mm_sub_epi32(_mm_set_epi32(1020, 1020, 1020, 1020), t47);
        m89 = _mm_add_epi32(s142, t47);
        m90 = _mm_add_epi32(s143, t48);
        m91 = _mm_add_epi32(s142, t48);
        m92 = _mm_add_epi32(s143, t47);
        d45 = _mm_cmpgt_epi32(m89, m90);
        d46 = _mm_cmpgt_epi32(m91, m92);
        a931 = _mm_andnot_si128(d45, m89);
        a932 = _mm_and_si128(d45, m90);
        s144 = _mm_or_si128(a931, a932);
        a933 = _mm_andnot_si128(d46, m91);
        a934 = _mm_and_si128(d46, m92);
        s145 = _mm_or_si128(a933, a934);
        s146 = _mm_movemask_epi8(_mm_packs_epi16(_mm_unpacklo_epi16(_mm_packs_epi16(d45,_mm_setzero_si128()),_mm_packs_epi16(d46,_mm_setzero_si128())),_mm_setzero_si128()));
        a935 = (a851 + 4);
        *(a935) = s146;
        s147 = _mm_unpacklo_epi32(s144, s145);
        s148 = _mm_unpackhi_epi32(s144, s145);
        a936 = (a852 + 8);
        *(a936) = s147;
        a937 = (a852 + 9);
        *(a937) = s148;
        a938 = (a818 + 5);
        s149 = *(a938);
        a939 = (a818 + 13);
        s150 = *(a939);
        a940 = (a824 + 5);
        a941 = *(a940);
        a942 = _mm_xor_si128(a823, a941);
        a943 = (a824 + 13);
        a944 = *(a943);
        a945 = _mm_xor_si128(a829, a944);
        a946 = (a824 + 21);
        a947 = *(a946);
        a948 = _mm_xor_si128(a835, a947);
        a949 = (a824 + 29);
        a950 = *(a949);
        a951 = _mm_xor_si128(a841, a950);
        b115 = _mm_add_epi32(a942, a945);
        b116 = _mm_add_epi32(b115, a948);
        t49 = _mm_add_epi32(b116, a951);
        t50 = _mm_sub_epi32(_mm_set_epi32(1020, 1020, 1020, 1020), t49);
        m93 = _mm_add_epi32(s149, t49);
        m94 = _mm_add_epi32(s150, t50);
        m95 = _mm_add_epi32(s149, t50);
        m96 = _mm_add_epi32(s150, t49);
        d47 = _mm_cmpgt_epi32(m93, m94);
        d48 = _mm_cmpgt_epi32(m95, m96);
        a952 = _mm_andnot_si128(d47, m93);
        a953 = _mm_and_si128(d47, m94);
        s151 = _mm_or_si128(a952, a953);
        a954 = _mm_andnot_si128(d48, m95);
        a955 = _mm_and_si128(d48, m96);
        s152 = _mm_or_si128(a954, a955);
        s153 = _mm_movemask_epi8(_mm_packs_epi16(_mm_unpacklo_epi16(_mm_packs_epi16(d47,_mm_setzero_si128()),_mm_packs_epi16(d48,_mm_setzero_si128())),_mm_setzero_si128()));
        a956 = (a851 + 5);
        *(a956) = s153;
        s154 = _mm_unpacklo_epi32(s151, s152);
        s155 = _mm_unpackhi_epi32(s151, s152);
        a957 = (a852 + 10);
        *(a957) = s154;
        a958 = (a852 + 11);
        *(a958) = s155;
        a959 = (a818 + 6);
        s156 = *(a959);
        a960 = (a818 + 14);
        s157 = *(a960);
        a961 = (a824 + 6);
        a962 = *(a961);
        a963 = _mm_xor_si128(a823, a962);
        a964 = (a824 + 14);
        a965 = *(a964);
        a966 = _mm_xor_si128(a829, a965);
        a967 = (a824 + 22);
        a968 = *(a967);
        a969 = _mm_xor_si128(a835, a968);
        a970 = (a824 + 30);
        a971 = *(a970);
        a972 = _mm_xor_si128(a841, a971);
        b117 = _mm_add_epi32(a963, a966);
        b118 = _mm_add_epi32(b117, a969);
        t51 = _mm_add_epi32(b118, a972);
        t52 = _mm_sub_epi32(_mm_set_epi32(1020, 1020, 1020, 1020), t51);
        m97 = _mm_add_epi32(s156, t51);
        m98 = _mm_add_epi32(s157, t52);
        m99 = _mm_add_epi32(s156, t52);
        m100 = _mm_add_epi32(s157, t51);
        d49 = _mm_cmpgt_epi32(m97, m98);
        d50 = _mm_cmpgt_epi32(m99, m100);
        a973 = _mm_andnot_si128(d49, m97);
        a974 = _mm_and_si128(d49, m98);
        s158 = _mm_or_si128(a973, a974);
        a975 = _mm_andnot_si128(d50, m99);
        a976 = _mm_and_si128(d50, m100);
        s159 = _mm_or_si128(a975, a976);
        s160 = _mm_movemask_epi8(_mm_packs_epi16(_mm_unpacklo_epi16(_mm_packs_epi16(d49,_mm_setzero_si128()),_mm_packs_epi16(d50,_mm_setzero_si128())),_mm_setzero_si128()));
        a977 = (a851 + 6);
        *(a977) = s160;
        s161 = _mm_unpacklo_epi32(s158, s159);
        s162 = _mm_unpackhi_epi32(s158, s159);
        a978 = (a852 + 12);
        *(a978) = s161;
        a979 = (a852 + 13);
        *(a979) = s162;
        a980 = (a818 + 7);
        s163 = *(a980);
        a981 = (a818 + 15);
        s164 = *(a981);
        a982 = (a824 + 7);
        a983 = *(a982);
        a984 = _mm_xor_si128(a823, a983);
        a985 = (a824 + 15);
        a986 = *(a985);
        a987 = _mm_xor_si128(a829, a986);
        a988 = (a824 + 23);
        a989 = *(a988);
        a990 = _mm_xor_si128(a835, a989);
        a991 = (a824 + 31);
        a992 = *(a991);
        a993 = _mm_xor_si128(a841, a992);
        b119 = _mm_add_epi32(a984, a987);
        b120 = _mm_add_epi32(b119, a990);
        t53 = _mm_add_epi32(b120, a993);
        t54 = _mm_sub_epi32(_mm_set_epi32(1020, 1020, 1020, 1020), t53);
        m101 = _mm_add_epi32(s163, t53);
        m102 = _mm_add_epi32(s164, t54);
        m103 = _mm_add_epi32(s163, t54);
        m104 = _mm_add_epi32(s164, t53);
        d51 = _mm_cmpgt_epi32(m101, m102);
        d52 = _mm_cmpgt_epi32(m103, m104);
        a994 = _mm_andnot_si128(d51, m101);
        a995 = _mm_and_si128(d51, m102);
        s165 = _mm_or_si128(a994, a995);
        a996 = _mm_andnot_si128(d52, m103);
        a997 = _mm_and_si128(d52, m104);
        s166 = _mm_or_si128(a996, a997);
        s167 = _mm_movemask_epi8(_mm_packs_epi16(_mm_unpacklo_epi16(_mm_packs_epi16(d51,_mm_setzero_si128()),_mm_packs_epi16(d52,_mm_setzero_si128())),_mm_setzero_si128()));
        a998 = (a851 + 7);
        *(a998) = s167;
        s168 = _mm_unpacklo_epi32(s165, s166);
        s169 = _mm_unpackhi_epi32(s165, s166);
        a999 = (a852 + 14);
        *(a999) = s168;
        a1000 = (a852 + 15);
        *(a1000) = s169;
        s170 = *(a852);
        s171 = *(a936);
        a1001 = (b104 + 4);
        a1002 = *(a1001);
        a1003 = _mm_set1_epi32(a1002);
        a1004 = _mm_xor_si128(a1003, a825);
        a1005 = (b104 + 5);
        a1006 = *(a1005);
        a1007 = _mm_set1_epi32(a1006);
        a1008 = _mm_xor_si128(a1007, a831);
        a1009 = (b104 + 6);
        a1010 = *(a1009);
        a1011 = _mm_set1_epi32(a1010);
        a1012 = _mm_xor_si128(a1011, a837);
        a1013 = (b104 + 7);
        a1014 = *(a1013);
        a1015 = _mm_set1_epi32(a1014);
        a1016 = _mm_xor_si128(a1015, a843);
        b121 = _mm_add_epi32(a1004, a1008);
        b122 = _mm_add_epi32(b121, a1012);
        t55 = _mm_add_epi32(b122, a1016);
        t56 = _mm_sub_epi32(_mm_set_epi32(1020, 1020, 1020, 1020), t55);
        m105 = _mm_add_epi32(s170, t55);
        m106 = _mm_add_epi32(s171, t56);
        m107 = _mm_add_epi32(s170, t56);
        m108 = _mm_add_epi32(s171, t55);
        d53 = _mm_cmpgt_epi32(m105, m106);
        d54 = _mm_cmpgt_epi32(m107, m108);
        a1017 = _mm_andnot_si128(d53, m105);
        a1018 = _mm_and_si128(d53, m106);
        s172 = _mm_or_si128(a1017, a1018);
        a1019 = _mm_andnot_si128(d54, m107);
        a1020 = _mm_and_si128(d54, m108);
        s173 = _mm_or_si128(a1019, a1020);
        s174 = _mm_movemask_epi8(_mm_packs_epi16(_mm_unpacklo_epi16(_mm_packs_epi16(d53,_mm_setzero_si128()),_mm_packs_epi16(d54,_mm_setzero_si128())),_mm_setzero_si128()));
        a1021 = (a851 + 8);
        *(a1021) = s174;
        s175 = _mm_unpacklo_epi32(s172, s173);
        s176 = _mm_unpackhi_epi32(s172, s173);
        *(a818) = s175;
        *(a854) = s176;
        s177 = *(a853);
        s178 = *(a937);
        a1022 = _mm_xor_si128(a1003, a857);
        a1023 = _mm_xor_si128(a1007, a860);
        a1024 = _mm_xor_si128(a1011, a863);
        a1025 = _mm_xor_si128(a1015, a866);
        b123 = _mm_add_epi32(a1022, a1023);
        b124 = _mm_add_epi32(b123, a1024);
        t57 = _mm_add_epi32(b124, a1025);
        t58 = _mm_sub_epi32(_mm_set_epi32(1020, 1020, 1020, 1020), t57);
        m109 = _mm_add_epi32(s177, t57);
        m110 = _mm_add_epi32(s178, t58);
        m111 = _mm_add_epi32(s177, t58);
        m112 = _mm_add_epi32(s178, t57);
        d55 = _mm_cmpgt_epi32(m109, m110);
        d56 = _mm_cmpgt_epi32(m111, m112);
        a1026 = _mm_andnot_si128(d55, m109);
        a1027 = _mm_and_si128(d55, m110);
        s179 = _mm_or_si128(a1026, a1027);
        a1028 = _mm_andnot_si128(d56, m111);
        a1029 = _mm_and_si128(d56, m112);
        s180 = _mm_or_si128(a1028, a1029);
        s181 = _mm_movemask_epi8(_mm_packs_epi16(_mm_unpacklo_epi16(_mm_packs_epi16(d55,_mm_setzero_si128()),_mm_packs_epi16(d56,_mm_setzero_si128())),_mm_setzero_si128()));
        a1030 = (a851 + 9);
        *(a1030) = s181;
        s182 = _mm_unpacklo_epi32(s179, s180);
        s183 = _mm_unpackhi_epi32(s179, s180);
        *(a875) = s182;
        *(a896) = s183;
        s184 = *(a873);
        s185 = *(a957);
        a1031 = _mm_xor_si128(a1003, a878);
        a1032 = _mm_xor_si128(a1007, a881);
        a1033 = _mm_xor_si128(a1011, a884);
        a1034 = _mm_xor_si128(a1015, a887);
        b125 = _mm_add_epi32(a1031, a1032);
        b126 = _mm_add_epi32(b125, a1033);
        t59 = _mm_add_epi32(b126, a1034);
        t60 = _mm_sub_epi32(_mm_set_epi32(1020, 1020, 1020, 1020), t59);
        m113 = _mm_add_epi32(s184, t59);
        m114 = _mm_add_epi32(s185, t60);
        m115 = _mm_add_epi32(s184, t60);
        m116 = _mm_add_epi32(s185, t59);
        d57 = _mm_cmpgt_epi32(m113, m114);
        d58 = _mm_cmpgt_epi32(m115, m116);
        a1035 = _mm_andnot_si128(d57, m113);
        a1036 = _mm_and_si128(d57, m114);
        s186 = _mm_or_si128(a1035, a1036);
        a1037 = _mm_andnot_si128(d58, m115);
        a1038 = _mm_and_si128(d58, m116);
        s187 = _mm_or_si128(a1037, a1038);
        s188 = _mm_movemask_epi8(_mm_packs_epi16(_mm_unpacklo_epi16(_mm_packs_epi16(d57,_mm_setzero_si128()),_mm_packs_epi16(d58,_mm_setzero_si128())),_mm_setzero_si128()));
        a1039 = (a851 + 10);
        *(a1039) = s188;
        s189 = _mm_unpacklo_epi32(s186, s187);
        s190 = _mm_unpackhi_epi32(s186, s187);
        *(a917) = s189;
        *(a938) = s190;
        s191 = *(a874);
        s192 = *(a958);
        a1040 = _mm_xor_si128(a1003, a899);
        a1041 = _mm_xor_si128(a1007, a902);
        a1042 = _mm_xor_si128(a1011, a905);
        a1043 = _mm_xor_si128(a1015, a908);
        b127 = _mm_add_epi32(a1040, a1041);
        b128 = _mm_add_epi32(b127, a1042);
        t61 = _mm_add_epi32(b128, a1043);
        t62 = _mm_sub_epi32(_mm_set_epi32(1020, 1020, 1020, 1020), t61);
        m117 = _mm_add_epi32(s191, t61);
        m118 = _mm_add_epi32(s192, t62);
        m119 = _mm_add_epi32(s191, t62);
        m120 = _mm_add_epi32(s192, t61);
        d59 = _mm_cmpgt_epi32(m117, m118);
        d60 = _mm_cmpgt_epi32(m119, m120);
        a1044 = _mm_andnot_si128(d59, m117);
        a1045 = _mm_and_si128(d59, m118);
        s193 = _mm_or_si128(a1044, a1045);
        a1046 = _mm_andnot_si128(d60, m119);
        a1047 = _mm_and_si128(d60, m120);
        s194 = _mm_or_si128(a1046, a1047);
        s195 = _mm_movemask_epi8(_mm_packs_epi16(_mm_unpacklo_epi16(_mm_packs_epi16(d59,_mm_setzero_si128()),_mm_packs_epi16(d60,_mm_setzero_si128())),_mm_setzero_si128()));
        a1048 = (a851 + 11);
        *(a1048) = s195;
        s196 = _mm_unpacklo_epi32(s193, s194);
        s197 = _mm_unpackhi_epi32(s193, s194);
        *(a959) = s196;
        *(a980) = s197;
        s198 = *(a894);
        s199 = *(a978);
        a1049 = _mm_xor_si128(a1003, a920);
        a1050 = _mm_xor_si128(a1007, a923);
        a1051 = _mm_xor_si128(a1011, a926);
        a1052 = _mm_xor_si128(a1015, a929);
        b129 = _mm_add_epi32(a1049, a1050);
        b130 = _mm_add_epi32(b129, a1051);
        t63 = _mm_add_epi32(b130, a1052);
        t64 = _mm_sub_epi32(_mm_set_epi32(1020, 1020, 1020, 1020), t63);
        m121 = _mm_add_epi32(s198, t63);
        m122 = _mm_add_epi32(s199, t64);
        m123 = _mm_add_epi32(s198, t64);
        m124 = _mm_add_epi32(s199, t63);
        d61 = _mm_cmpgt_epi32(m121, m122);
        d62 = _mm_cmpgt_epi32(m123, m124);
        a1053 = _mm_andnot_si128(d61, m121);
        a1054 = _mm_and_si128(d61, m122);
        s200 = _mm_or_si128(a1053, a1054);
        a1055 = _mm_andnot_si128(d62, m123);
        a1056 = _mm_and_si128(d62, m124);
        s201 = _mm_or_si128(a1055, a1056);
        s202 = _mm_movemask_epi8(_mm_packs_epi16(_mm_unpacklo_epi16(_mm_packs_epi16(d61,_mm_setzero_si128()),_mm_packs_epi16(d62,_mm_setzero_si128())),_mm_setzero_si128()));
        a1057 = (a851 + 12);
        *(a1057) = s202;
        s203 = _mm_unpacklo_epi32(s200, s201);
        s204 = _mm_unpackhi_epi32(s200, s201);
        *(a819) = s203;
        *(a855) = s204;
        s205 = *(a895);
        s206 = *(a979);
        a1058 = _mm_xor_si128(a1003, a941);
        a1059 = _mm_xor_si128(a1007, a944);
        a1060 = _mm_xor_si128(a1011, a947);
        a1061 = _mm_xor_si128(a1015, a950);
        b131 = _mm_add_epi32(a1058, a1059);
        b132 = _mm_add_epi32(b131, a1060);
        t65 = _mm_add_epi32(b132, a1061);
        t66 = _mm_sub_epi32(_mm_set_epi32(1020, 1020, 1020, 1020), t65);
        m125 = _mm_add_epi32(s205, t65);
        m126 = _mm_add_epi32(s206, t66);
        m127 = _mm_add_epi32(s205, t66);
        m128 = _mm_add_epi32(s206, t65);
        d63 = _mm_cmpgt_epi32(m125, m126);
        d64 = _mm_cmpgt_epi32(m127, m128);
        a1062 = _mm_andnot_si128(d63, m125);
        a1063 = _mm_and_si128(d63, m126);
        s207 = _mm_or_si128(a1062, a1063);
        a1064 = _mm_andnot_si128(d64, m127);
        a1065 = _mm_and_si128(d64, m128);
        s208 = _mm_or_si128(a1064, a1065);
        s209 = _mm_movemask_epi8(_mm_packs_epi16(_mm_unpacklo_epi16(_mm_packs_epi16(d63,_mm_setzero_si128()),_mm_packs_epi16(d64,_mm_setzero_si128())),_mm_setzero_si128()));
        a1066 = (a851 + 13);
        *(a1066) = s209;
        s210 = _mm_unpacklo_epi32(s207, s208);
        s211 = _mm_unpackhi_epi32(s207, s208);
        *(a876) = s210;
        *(a897) = s211;
        s212 = *(a915);
        s213 = *(a999);
        a1067 = _mm_xor_si128(a1003, a962);
        a1068 = _mm_xor_si128(a1007, a965);
        a1069 = _mm_xor_si128(a1011, a968);
        a1070 = _mm_xor_si128(a1015, a971);
        b133 = _mm_add_epi32(a1067, a1068);
        b134 = _mm_add_epi32(b133, a1069);
        t67 = _mm_add_epi32(b134, a1070);
        t68 = _mm_sub_epi32(_mm_set_epi32(1020, 1020, 1020, 1020), t67);
        m129 = _mm_add_epi32(s212, t67);
        m130 = _mm_add_epi32(s213, t68);
        m131 = _mm_add_epi32(s212, t68);
        m132 = _mm_add_epi32(s213, t67);
        d65 = _mm_cmpgt_epi32(m129, m130);
        d66 = _mm_cmpgt_epi32(m131, m132);
        a1071 = _mm_andnot_si128(d65, m129);
        a1072 = _mm_and_si128(d65, m130);
        s214 = _mm_or_si128(a1071, a1072);
        a1073 = _mm_andnot_si128(d66, m131);
        a1074 = _mm_and_si128(d66, m132);
        s215 = _mm_or_si128(a1073, a1074);
        s216 = _mm_movemask_epi8(_mm_packs_epi16(_mm_unpacklo_epi16(_mm_packs_epi16(d65,_mm_setzero_si128()),_mm_packs_epi16(d66,_mm_setzero_si128())),_mm_setzero_si128()));
        a1075 = (a851 + 14);
        *(a1075) = s216;
        s217 = _mm_unpacklo_epi32(s214, s215);
        s218 = _mm_unpackhi_epi32(s214, s215);
        *(a918) = s217;
        *(a939) = s218;
        s219 = *(a916);
        s220 = *(a1000);
        a1076 = _mm_xor_si128(a1003, a983);
        a1077 = _mm_xor_si128(a1007, a986);
        a1078 = _mm_xor_si128(a1011, a989);
        a1079 = _mm_xor_si128(a1015, a992);
        b135 = _mm_add_epi32(a1076, a1077);
        b136 = _mm_add_epi32(b135, a1078);
        t69 = _mm_add_epi32(b136, a1079);
        t70 = _mm_sub_epi32(_mm_set_epi32(1020, 1020, 1020, 1020), t69);
        m133 = _mm_add_epi32(s219, t69);
        m134 = _mm_add_epi32(s220, t70);
        m135 = _mm_add_epi32(s219, t70);
        m136 = _mm_add_epi32(s220, t69);
        d67 = _mm_cmpgt_epi32(m133, m134);
        d68 = _mm_cmpgt_epi32(m135, m136);
        a1080 = _mm_andnot_si128(d67, m133);
        a1081 = _mm_and_si128(d67, m134);
        s221 = _mm_or_si128(a1080, a1081);
        a1082 = _mm_andnot_si128(d68, m135);
        a1083 = _mm_and_si128(d68, m136);
        s222 = _mm_or_si128(a1082, a1083);
        s223 = _mm_movemask_epi8(_mm_packs_epi16(_mm_unpacklo_epi16(_mm_packs_epi16(d67,_mm_setzero_si128()),_mm_packs_epi16(d68,_mm_setzero_si128())),_mm_setzero_si128()));
        a1084 = (a851 + 15);
        *(a1084) = s223;
        s224 = _mm_unpacklo_epi32(s221, s222);
        s225 = _mm_unpackhi_epi32(s221, s222);
        *(a960) = s224;
        *(a981) = s225;
    }
    /* skip */
}

#else

void FULL_SPIRAL (int amount, unsigned int  *Y, unsigned int  *X, unsigned int  *syms, unsigned int  *dec, unsigned int  *Branchtab) {
int i3;
    for(i3 = 0; i3 < amount; i3++) {
//    for(i3 = 0; i3 <= amount; i3++) {
        int a2082, a2083, a2084, a2085, a2086, a2087, a2088
                , a2089, a2090, a2091, a2092, a2093, a2094, a2095, a2096
                , a2097, a2098, a2099, a2100, a2101, a2102, a2103, a2104
                , a2105, a2106, a2107, a2108, a2109, a2110, a2111, a2112
                , a2113, a2114, a2115, a2116, a2117, a2118, a2119, a2120
                , a2121, a2122, a2123, a2124, a2125, a2126, a2127, a2128
                , a2129, a2130, a2131, a2132, a2133, a2134, a2135, a2136
                , a2137, a2138, a2139, a2140, a2141, a2142, a2143, a2144
                , a2145, a2146, a2147, a2148, a2149, a2150, a2151, a2152
                , a2153, a2154, a2155, a2156, a2157, a2158, a2159, a2160
                , a2161, a2162, a2163, a2164, a2165, a2166, a2167, a2168
                , a2169, a2170, a2171, a2172, a2173, a2174, a2175, a2176
                , a2177, a2178, a2179, a2180, a2181, a2182, a2183, a2184
                , a2185, a2186, a2187, a2188, a2189, a2190, a2191, a2192
                , a2193, a2194, a2195, a2196, a2197, a2198, a2199, a2200
                , a2201, a2202, a2203, a2204, a2205, a2206, a2207, a2208
                , a2209, a2210, a2211, a2212, a2213, a2214, a2215, a2216
                , a2217, a2218, a2219, a2220, a2221, a2222, a2223, a2224
                , a2225, a2226, a2227, a2228, a2229, a2230, a2231, a2232
                , a2233, a2234, a2235, a2236, a2237, a2238, a2239, a2240
                , a2241, a2242, a2243, a2244, a2245, a2246, a2247, a2248
                , a2249, a2250, a2251, a2252, a2253, a2254, a2255, a2256
                , a2257, a2258, a2259, a2260, a2261, a2262, a2263, a2264
                , a2265, a2266, a2267, a2268, a2269, a2270, a2271, a2272
                , a2273, a2274, a2275, a2276, a2277, a2278, a2279, a2280
                , a2281, a2282, a2283, a2284, a2285, a2286, a2287, a2288
                , a2289, a2290, a2291, a2292, a2293, a2294, a2295, a2296
                , a2297, a2298, a2299, a2300, a2301, a2302, a2303, a2304
                , a2305, a2306, a2307, a2308, a2309, a2310, a2311, a2312
                , a2313, a2314, a2315, a2316, a2317, a2318, a2319, a2320
                , a2321, a2322, a2323, a2324, a2325, a2326, a2327, a2328
                , a2329, a2330, a2331, a2332, a2333, a2334, a2335, a2336
                , a2337, a2338, a2339, a2340, a2341, a2342, a2343, a2344
                , a2345, a2346, a2347, a2348, a2349, a2350, a2351, a2352
                , a2353, a2354, a2355, a2356, a2357, a2358, a2359, a2360
                , a2361, a2362, a2363, a2364, a2365, a2366, a2367, a2368
                , a2369, a2370, a2371, a2372, a2373, a2374, a2375, a2376
                , a2377, a2378, a2379, a2380, a2381, a2382, a2383, a2384
                , a2385, a2386, a2387, a2388, a2389, a2390, a2391, a2392
                , a2393, a2394, a2395, a2396, a2397, a2398, a2399, a2400
                , a2401, a2402, a2403, a2404, a2405, a2406, a2407, a2408
                , a2409, a2410, a2411, a2412, a2413, a2414, a2415, a2416
                , a2417, a2418, a2419, a2420, a2421, a2422, a2423, a2424
                , a2425, a2426, a2427, a2428, a2429, a2430, a2431, a2432
                , a2433, a2434, a2435, a2436, a2437, a2438, a2439, a2440
                , a2441, a2442, a2443, a2444, a2445, a2446, a2447, a2448
                , a2449, a2450, a2451, a2452, a2453, a2454, a2455, a2456
                , a2457, a2458, a2459, a2460, a2461, a2462, a2463, a2464
                , a2465, a2466, a2467, a2468, a2469, a2470, a2471, a2472
                , a2473, a2474, a2475, a2476, a2477, a2478, a2479, a2480
                , a2481, a2482, a2483, a2484, a2485, a2486, a2487, a2488
                , a2489, a2490, a2491, a2492, a2493, a2494, a2495, a2496
                , a2497, a2498, a2499, a2500, a2501, a2502, a2503, a2504
                , a2505, a2506, a2507, a2508, a2509, a2510, a2511, a2512
                , a2513, a2514, a2515, a2516, a2517, a2518, a2519, a2520
                , a2521, a2522, a2523, a2524, a2525, a2526, a2527, a2528
                , a2529, a2530, a2531, a2532, a2533, a2534, a2535, a2536
                , a2537, a2538, a2539, a2540, a2541, a2542, a2543, a2544
                , a2545, a2546, a2547, a2548, a2549, a2550, a2551;
        unsigned int d133, d134, d135, d136, d137, d138, d139
                , d140, d141, d142, d143, d144, d145, d146, d147
                , d148, d149, d150, d151, d152, d153, d154, d155
                , d156, d157, d158, d159, d160, d161, d162, d163
                , d164, d165, d166, d167, d168, d169, d170, d171
                , d172, d173, d174, d175, d176, d177, d178, d179
                , d180, d181, d182, d183, d184, d185, d186, d187
                , d188, d189, d190, d191, d192, d193, d194, d195
                , d196, d197, d198, d199, d200, d201, d202, d203
                , d204, d205, d206, d207, d208, d209, d210, d211
                , d212, d213, d214, d215, d216, d217, d218, d219
                , d220, d221, d222, d223, d224, d225, d226, d227
                , d228, d229, d230, d231, d232, d233, d234, d235
                , d236, d237, d238, d239, d240, d241, d242, d243
                , d244, d245, d246, d247, d248, d249, d250, d251
                , d252, d253, d254, d255, d256, d257, d258, d259
                , d260, m265, m266, m267, m268, m269, m270, m271
                , m272, m273, m274, m275, m276, m277, m278, m279
                , m280, m281, m282, m283, m284, m285, m286, m287
                , m288, m289, m290, m291, m292, m293, m294, m295
                , m296, m297, m298, m299, m300, m301, m302, m303
                , m304, m305, m306, m307, m308, m309, m310, m311
                , m312, m313, m314, m315, m316, m317, m318, m319
                , m320, m321, m322, m323, m324, m325, m326, m327
                , m328, m329, m330, m331, m332, m333, m334, m335
                , m336, m337, m338, m339, m340, m341, m342, m343
                , m344, m345, m346, m347, m348, m349, m350, m351
                , m352, m353, m354, m355, m356, m357, m358, m359
                , m360, m361, m362, m363, m364, m365, m366, m367
                , m368, m369, m370, m371, m372, m373, m374, m375
                , m376, m377, m378, m379, m380, m381, m382, m383
                , m384, m385, m387, m388, m389, m390, m391, m392
                , m393, m394, m395, m396, m397, m398, m399, m400
                , m401, m402, m403, m404, m405, m406, m407, m408
                , m409, m410, m411, m412, m413, m414, m415, m416
                , m417, m418, m419, m420, m421, m422, m423, m424
                , m425, m426, m427, m428, m429, m430, m431, m432
                , m433, m434, m435, m436, m437, m438, m439, m440
                , m441, m442, m443, m444, m445, m446, m447, m448
                , m449, m450, m451, m452, m453, m454, m455, m456
                , m457, m458, m459, m460, m461, m462, m463, m464
                , m465, m466, m467, m468, m469, m470, m471, m472
                , m473, m474, m475, m476, m477, m478, m479, m480
                , m481, m482, m483, m484, m485, m486, m487, m488
                , m489, m490, m491, m492, m493, m494, m495, m496
                , m497, m498, m499, m500, m501, m502, m503, m504
                , m505, m506, m507, m508, m509, m510, m511, m512
                , m513, m514, m515, m516, m517, m518, m519, m520
                , m521, s130, s131, s132, s133, s134, s135, s136
                , s137, s138, s139, s140, s141, s142, s143, s144
                , s145, s146, s147, s148, s149, s150, s151, s152
                , s153, s154, s155, s156, s157, s158, s159, s160
                , s161, s162, s163, s164, s165, s166, s167, s168
                , s169, s170, s171, s172, s173, s174, s175, s176
                , s177, s178, s179, s180, s181, s182, s183, s184
                , s185, s186, s187, s188, s189, s190, s191, s192
                , s193, s194, s195, s196, s197, s198, s199, s200
                , s201, s202, s203, s204, s205, s206, s207, s208
                , s209, s210, s211, s212, s213, s214, s215, s216
                , s217, s218, s219, s220, s221, s222, s223, s224
                , s225, s226, s227, s228, s229, s230, s231, s232
                , s233, s234, s235, s236, s237, s238, s239, s240
                , s241, s242, s243, s244, s245, s246, s247, s248
                , s249, s250, s251, s252, s253, s254, s255, s256
                , s257, t325, t326, t327, t328, t329, t330, t331
                , t332, t333, t334, t335, t336, t337, t338, t339
                , t340, t341, t342, t343, t344, t345, t346, t347
                , t348, t349, t350, t351, t352, t353, t354, t355
                , t356, t357, t358, t359, t360, t361, t362, t363
                , t364, t365, t366, t367, t368, t369, t370, t371
                , t372, t373, t374, t375, t376, t377, t378, t379
                , t380, t381, t382, t383, t384, t385, t387, t388
                , t389, t390, t391, t392, t393, t394, t395, t396
                , t397, t398, t399, t400, t401, t402, t403, t404
                , t405, t406, t407, t408, t409, t410, t411, t412
                , t413, t414, t415, t416, t417, t418, t419, t420
                , t421, t422, t423, t424, t425, t426, t427, t428
                , t429, t430, t431, t432, t433, t434, t435, t436
                , t437, t438, t439, t440, t441, t442, t443, t444
                , t445, t446, t447, t448, t449, t450, t451, t452
                , t453, t454, t455, t456, t457, t458, t459, t460
                , t461, t462, t463, t464, t465, t466, t467, t468
                , t469, t470, t471, t472, t473, t474, t475, t476
                , t477, t478, t479, t480, t481, t482, t483, t484
                , t485, t486, t487, t488, t489, t490, t491, t492
                , t493, t494, t495, t496, t497, t498, t499, t500
                , t501, t502, t503, t504, t505, t506, t507, t508
                , t509, t510, t511, t512, t513, t514, t515, t516
                , t517, t518, t519, t520, t521, t522, t523, t524
                , t525, t526, t527, t528, t529, t530, t531, t532
                , t533, t534, t535, t536, t537, t538, t539, t540
                , t541, t542, t543, t544, t545, t546, t547, t548
                , t549, t550, t551, t552, t553, t554, t555, t556
                , t557, t558, t559, t560, t561, t562, t563, t564
                , t565, t566, t567, t568, t569, t570, t571, t572
                , t573, t574, t575, t576, t577, t578, t579, t580
                , t581, t582, t583, t584, t585, t586, t587, t588
                , t589, t590, t591, t592, t593, t594, t595, t596
                , t597, t598, t599, t600, t601, t602, t603, t604
                , t605, t606, t607, t608, t609, t610, t611, t612
                , t613, t614, t615, t616, t617, t618, t619, t620
                , t621, t622, t623, t624, t625, t626, t627, t628
                , t629, t630, t631, t632, t633, t634, t635, t636
                , t637, t638, t639, t640, t641, t642, t643, t644
                , t645;
        a2082 = (8*i3);
        a2083 = syms[a2082];
        t325 = ((a2083)^(Branchtab[0]));
        a2084 = (1 + a2082);
        a2085 = syms[a2084];
        a2086 = ((a2085)^(Branchtab[32]));
        t326 = (t325 + a2086);
        a2087 = (2 + a2082);
        a2088 = syms[a2087];
        a2089 = ((a2088)^(Branchtab[64]));
        t327 = (t326 + a2089);
        a2090 = (3 + a2082);
        a2091 = syms[a2090];
        a2092 = ((a2091)^(Branchtab[96]));
        t328 = (t327 + a2092);
        t329 = (1020 - t328);
        m265 = (X[0] + t328);
        m266 = (X[32] + t329);
        m267 = (X[0] + t329);
        m268 = (X[32] + t328);
        d133 = ((m265 > m266));
        d134 = ((m267 > m268));
        s130 = ((d133) ? (m266) : (m265));
        s131 = ((d134) ? (m268) : (m267));
        a2093 = (2*i3);
        a2094 = ((a2093) << (1));
        a2095 = dec[a2094];
        a2096 = ((d134) << (1));
        a2097 = ((d133)|(a2096));
        a2098 = ((a2097) << (0));
        dec[a2094] = ((a2095)|(a2098));
        Y[0] = s130;
        Y[1] = s131;
        t330 = ((a2083)^(Branchtab[1]));
        a2099 = ((a2085)^(Branchtab[33]));
        t331 = (t330 + a2099);
        a2100 = ((a2088)^(Branchtab[65]));
        t332 = (t331 + a2100);
        a2101 = ((a2091)^(Branchtab[97]));
        t333 = (t332 + a2101);
        t334 = (1020 - t333);
        m269 = (X[1] + t333);
        m270 = (X[33] + t334);
        m271 = (X[1] + t334);
        m272 = (X[33] + t333);
        d135 = ((m269 > m270));
        d136 = ((m271 > m272));
        s132 = ((d135) ? (m270) : (m269));
        s133 = ((d136) ? (m272) : (m271));
        a2102 = dec[a2094];
        a2103 = ((d136) << (1));
        a2104 = ((d135)|(a2103));
        a2105 = ((a2104) << (2));
        dec[a2094] = ((a2102)|(a2105));
        Y[2] = s132;
        Y[3] = s133;
        t335 = ((a2083)^(Branchtab[2]));
        a2106 = ((a2085)^(Branchtab[34]));
        t336 = (t335 + a2106);
        a2107 = ((a2088)^(Branchtab[66]));
        t337 = (t336 + a2107);
        a2108 = ((a2091)^(Branchtab[98]));
        t338 = (t337 + a2108);
        t339 = (1020 - t338);
        m273 = (X[2] + t338);
        m274 = (X[34] + t339);
        m275 = (X[2] + t339);
        m276 = (X[34] + t338);
        d137 = ((m273 > m274));
        d138 = ((m275 > m276));
        s134 = ((d137) ? (m274) : (m273));
        s135 = ((d138) ? (m276) : (m275));
        a2109 = dec[a2094];
        a2110 = ((d138) << (1));
        a2111 = ((d137)|(a2110));
        a2112 = ((a2111) << (4));
        dec[a2094] = ((a2109)|(a2112));
        Y[4] = s134;
        Y[5] = s135;
        t340 = ((a2083)^(Branchtab[3]));
        a2113 = ((a2085)^(Branchtab[35]));
        t341 = (t340 + a2113);
        a2114 = ((a2088)^(Branchtab[67]));
        t342 = (t341 + a2114);
        a2115 = ((a2091)^(Branchtab[99]));
        t343 = (t342 + a2115);
        t344 = (1020 - t343);
        m277 = (X[3] + t343);
        m278 = (X[35] + t344);
        m279 = (X[3] + t344);
        m280 = (X[35] + t343);
        d139 = ((m277 > m278));
        d140 = ((m279 > m280));
        s136 = ((d139) ? (m278) : (m277));
        s137 = ((d140) ? (m280) : (m279));
        a2116 = dec[a2094];
        a2117 = ((d140) << (1));
        a2118 = ((d139)|(a2117));
        a2119 = ((a2118) << (6));
        dec[a2094] = ((a2116)|(a2119));
        Y[6] = s136;
        Y[7] = s137;
        t345 = ((a2083)^(Branchtab[4]));
        a2120 = ((a2085)^(Branchtab[36]));
        t346 = (t345 + a2120);
        a2121 = ((a2088)^(Branchtab[68]));
        t347 = (t346 + a2121);
        a2122 = ((a2091)^(Branchtab[100]));
        t348 = (t347 + a2122);
        t349 = (1020 - t348);
        m281 = (X[4] + t348);
        m282 = (X[36] + t349);
        m283 = (X[4] + t349);
        m284 = (X[36] + t348);
        d141 = ((m281 > m282));
        d142 = ((m283 > m284));
        s138 = ((d141) ? (m282) : (m281));
        s139 = ((d142) ? (m284) : (m283));
        a2123 = dec[a2094];
        a2124 = ((d142) << (1));
        a2125 = ((d141)|(a2124));
        a2126 = ((a2125) << (8));
        dec[a2094] = ((a2123)|(a2126));
        Y[8] = s138;
        Y[9] = s139;
        t350 = ((a2083)^(Branchtab[5]));
        a2127 = ((a2085)^(Branchtab[37]));
        t351 = (t350 + a2127);
        a2128 = ((a2088)^(Branchtab[69]));
        t352 = (t351 + a2128);
        a2129 = ((a2091)^(Branchtab[101]));
        t353 = (t352 + a2129);
        t354 = (1020 - t353);
        m285 = (X[5] + t353);
        m286 = (X[37] + t354);
        m287 = (X[5] + t354);
        m288 = (X[37] + t353);
        d143 = ((m285 > m286));
        d144 = ((m287 > m288));
        s140 = ((d143) ? (m286) : (m285));
        s141 = ((d144) ? (m288) : (m287));
        a2130 = dec[a2094];
        a2131 = ((d144) << (1));
        a2132 = ((d143)|(a2131));
        a2133 = ((a2132) << (10));
        dec[a2094] = ((a2130)|(a2133));
        Y[10] = s140;
        Y[11] = s141;
        t355 = ((a2083)^(Branchtab[6]));
        a2134 = ((a2085)^(Branchtab[38]));
        t356 = (t355 + a2134);
        a2135 = ((a2088)^(Branchtab[70]));
        t357 = (t356 + a2135);
        a2136 = ((a2091)^(Branchtab[102]));
        t358 = (t357 + a2136);
        t359 = (1020 - t358);
        m289 = (X[6] + t358);
        m290 = (X[38] + t359);
        m291 = (X[6] + t359);
        m292 = (X[38] + t358);
        d145 = ((m289 > m290));
        d146 = ((m291 > m292));
        s142 = ((d145) ? (m290) : (m289));
        s143 = ((d146) ? (m292) : (m291));
        a2137 = dec[a2094];
        a2138 = ((d146) << (1));
        a2139 = ((d145)|(a2138));
        a2140 = ((a2139) << (12));
        dec[a2094] = ((a2137)|(a2140));
        Y[12] = s142;
        Y[13] = s143;
        t360 = ((a2083)^(Branchtab[7]));
        a2141 = ((a2085)^(Branchtab[39]));
        t361 = (t360 + a2141);
        a2142 = ((a2088)^(Branchtab[71]));
        t362 = (t361 + a2142);
        a2143 = ((a2091)^(Branchtab[103]));
        t363 = (t362 + a2143);
        t364 = (1020 - t363);
        m293 = (X[7] + t363);
        m294 = (X[39] + t364);
        m295 = (X[7] + t364);
        m296 = (X[39] + t363);
        d147 = ((m293 > m294));
        d148 = ((m295 > m296));
        s144 = ((d147) ? (m294) : (m293));
        s145 = ((d148) ? (m296) : (m295));
        a2144 = dec[a2094];
        a2145 = ((d148) << (1));
        a2146 = ((d147)|(a2145));
        a2147 = ((a2146) << (14));
        dec[a2094] = ((a2144)|(a2147));
        Y[14] = s144;
        Y[15] = s145;
        t365 = ((a2083)^(Branchtab[8]));
        a2148 = ((a2085)^(Branchtab[40]));
        t366 = (t365 + a2148);
        a2149 = ((a2088)^(Branchtab[72]));
        t367 = (t366 + a2149);
        a2150 = ((a2091)^(Branchtab[104]));
        t368 = (t367 + a2150);
        t369 = (1020 - t368);
        m297 = (X[8] + t368);
        m298 = (X[40] + t369);
        m299 = (X[8] + t369);
        m300 = (X[40] + t368);
        d149 = ((m297 > m298));
        d150 = ((m299 > m300));
        s146 = ((d149) ? (m298) : (m297));
        s147 = ((d150) ? (m300) : (m299));
        a2151 = dec[a2094];
        a2152 = ((d150) << (1));
        a2153 = ((d149)|(a2152));
        a2154 = ((a2153) << (16));
        dec[a2094] = ((a2151)|(a2154));
        Y[16] = s146;
        Y[17] = s147;
        t370 = ((a2083)^(Branchtab[9]));
        a2155 = ((a2085)^(Branchtab[41]));
        t371 = (t370 + a2155);
        a2156 = ((a2088)^(Branchtab[73]));
        t372 = (t371 + a2156);
        a2157 = ((a2091)^(Branchtab[105]));
        t373 = (t372 + a2157);
        t374 = (1020 - t373);
        m301 = (X[9] + t373);
        m302 = (X[41] + t374);
        m303 = (X[9] + t374);
        m304 = (X[41] + t373);
        d151 = ((m301 > m302));
        d152 = ((m303 > m304));
        s148 = ((d151) ? (m302) : (m301));
        s149 = ((d152) ? (m304) : (m303));
        a2158 = dec[a2094];
        a2159 = ((d152) << (1));
        a2160 = ((d151)|(a2159));
        a2161 = ((a2160) << (18));
        dec[a2094] = ((a2158)|(a2161));
        Y[18] = s148;
        Y[19] = s149;
        t375 = ((a2083)^(Branchtab[10]));
        a2162 = ((a2085)^(Branchtab[42]));
        t376 = (t375 + a2162);
        a2163 = ((a2088)^(Branchtab[74]));
        t377 = (t376 + a2163);
        a2164 = ((a2091)^(Branchtab[106]));
        t378 = (t377 + a2164);
        t379 = (1020 - t378);
        m305 = (X[10] + t378);
        m306 = (X[42] + t379);
        m307 = (X[10] + t379);
        m308 = (X[42] + t378);
        d153 = ((m305 > m306));
        d154 = ((m307 > m308));
        s150 = ((d153) ? (m306) : (m305));
        s151 = ((d154) ? (m308) : (m307));
        a2165 = dec[a2094];
        a2166 = ((d154) << (1));
        a2167 = ((d153)|(a2166));
        a2168 = ((a2167) << (20));
        dec[a2094] = ((a2165)|(a2168));
        Y[20] = s150;
        Y[21] = s151;
        t380 = ((a2083)^(Branchtab[11]));
        a2169 = ((a2085)^(Branchtab[43]));
        t381 = (t380 + a2169);
        a2170 = ((a2088)^(Branchtab[75]));
        t382 = (t381 + a2170);
        a2171 = ((a2091)^(Branchtab[107]));
        t383 = (t382 + a2171);
        t384 = (1020 - t383);
        m309 = (X[11] + t383);
        m310 = (X[43] + t384);
        m311 = (X[11] + t384);
        m312 = (X[43] + t383);
        d155 = ((m309 > m310));
        d156 = ((m311 > m312));
        s152 = ((d155) ? (m310) : (m309));
        s153 = ((d156) ? (m312) : (m311));
        a2172 = dec[a2094];
        a2173 = ((d156) << (1));
        a2174 = ((d155)|(a2173));
        a2175 = ((a2174) << (22));
        dec[a2094] = ((a2172)|(a2175));
        Y[22] = s152;
        Y[23] = s153;
        t385 = ((a2083)^(Branchtab[12]));
        a2176 = ((a2085)^(Branchtab[44]));
        t387 = (t385 + a2176);
        a2177 = ((a2088)^(Branchtab[76]));
        t388 = (t387 + a2177);
        a2178 = ((a2091)^(Branchtab[108]));
        t389 = (t388 + a2178);
        t390 = (1020 - t389);
        m313 = (X[12] + t389);
        m314 = (X[44] + t390);
        m315 = (X[12] + t390);
        m316 = (X[44] + t389);
        d157 = ((m313 > m314));
        d158 = ((m315 > m316));
        s154 = ((d157) ? (m314) : (m313));
        s155 = ((d158) ? (m316) : (m315));
        a2179 = dec[a2094];
        a2180 = ((d158) << (1));
        a2181 = ((d157)|(a2180));
        a2182 = ((a2181) << (24));
        dec[a2094] = ((a2179)|(a2182));
        Y[24] = s154;
        Y[25] = s155;
        t391 = ((a2083)^(Branchtab[13]));
        a2183 = ((a2085)^(Branchtab[45]));
        t392 = (t391 + a2183);
        a2184 = ((a2088)^(Branchtab[77]));
        t393 = (t392 + a2184);
        a2185 = ((a2091)^(Branchtab[109]));
        t394 = (t393 + a2185);
        t395 = (1020 - t394);
        m317 = (X[13] + t394);
        m318 = (X[45] + t395);
        m319 = (X[13] + t395);
        m320 = (X[45] + t394);
        d159 = ((m317 > m318));
        d160 = ((m319 > m320));
        s156 = ((d159) ? (m318) : (m317));
        s157 = ((d160) ? (m320) : (m319));
        a2186 = dec[a2094];
        a2187 = ((d160) << (1));
        a2188 = ((d159)|(a2187));
        a2189 = ((a2188) << (26));
        dec[a2094] = ((a2186)|(a2189));
        Y[26] = s156;
        Y[27] = s157;
        t396 = ((a2083)^(Branchtab[14]));
        a2190 = ((a2085)^(Branchtab[46]));
        t397 = (t396 + a2190);
        a2191 = ((a2088)^(Branchtab[78]));
        t398 = (t397 + a2191);
        a2192 = ((a2091)^(Branchtab[110]));
        t399 = (t398 + a2192);
        t400 = (1020 - t399);
        m321 = (X[14] + t399);
        m322 = (X[46] + t400);
        m323 = (X[14] + t400);
        m324 = (X[46] + t399);
        d161 = ((m321 > m322));
        d162 = ((m323 > m324));
        s158 = ((d161) ? (m322) : (m321));
        s159 = ((d162) ? (m324) : (m323));
        a2193 = dec[a2094];
        a2194 = ((d162) << (1));
        a2195 = ((d161)|(a2194));
        a2196 = ((a2195) << (28));
        dec[a2094] = ((a2193)|(a2196));
        Y[28] = s158;
        Y[29] = s159;
        t401 = ((a2083)^(Branchtab[15]));
        a2197 = ((a2085)^(Branchtab[47]));
        t402 = (t401 + a2197);
        a2198 = ((a2088)^(Branchtab[79]));
        t403 = (t402 + a2198);
        a2199 = ((a2091)^(Branchtab[111]));
        t404 = (t403 + a2199);
        t405 = (1020 - t404);
        m325 = (X[15] + t404);
        m326 = (X[47] + t405);
        m327 = (X[15] + t405);
        m328 = (X[47] + t404);
        d163 = ((m325 > m326));
        d164 = ((m327 > m328));
        s160 = ((d163) ? (m326) : (m325));
        s161 = ((d164) ? (m328) : (m327));
        a2200 = dec[a2094];
        a2201 = ((d164) << (1));
        a2202 = ((d163)|(a2201));
        a2203 = ((a2202) << (30));
        dec[a2094] = ((a2200)|(a2203));
        Y[30] = s160;
        Y[31] = s161;
        t406 = ((a2083)^(Branchtab[16]));
        a2204 = ((a2085)^(Branchtab[48]));
        t407 = (t406 + a2204);
        a2205 = ((a2088)^(Branchtab[80]));
        t408 = (t407 + a2205);
        a2206 = ((a2091)^(Branchtab[112]));
        t409 = (t408 + a2206);
        t410 = (1020 - t409);
        m329 = (X[16] + t409);
        m330 = (X[48] + t410);
        m331 = (X[16] + t410);
        m332 = (X[48] + t409);
        d165 = ((m329 > m330));
        d166 = ((m331 > m332));
        s162 = ((d165) ? (m330) : (m329));
        s163 = ((d166) ? (m332) : (m331));
        a2207 = (1 + a2094);
        a2208 = dec[a2207];
        a2209 = ((d166) << (1));
        a2210 = ((d165)|(a2209));
        a2211 = ((a2210) << (0));
        dec[a2207] = ((a2208)|(a2211));
        Y[32] = s162;
        Y[33] = s163;
        t411 = ((a2083)^(Branchtab[17]));
        a2212 = ((a2085)^(Branchtab[49]));
        t412 = (t411 + a2212);
        a2213 = ((a2088)^(Branchtab[81]));
        t413 = (t412 + a2213);
        a2214 = ((a2091)^(Branchtab[113]));
        t414 = (t413 + a2214);
        t415 = (1020 - t414);
        m333 = (X[17] + t414);
        m334 = (X[49] + t415);
        m335 = (X[17] + t415);
        m336 = (X[49] + t414);
        d167 = ((m333 > m334));
        d168 = ((m335 > m336));
        s164 = ((d167) ? (m334) : (m333));
        s165 = ((d168) ? (m336) : (m335));
        a2215 = dec[a2207];
        a2216 = ((d168) << (1));
        a2217 = ((d167)|(a2216));
        a2218 = ((a2217) << (2));
        dec[a2207] = ((a2215)|(a2218));
        Y[34] = s164;
        Y[35] = s165;
        t416 = ((a2083)^(Branchtab[18]));
        a2219 = ((a2085)^(Branchtab[50]));
        t417 = (t416 + a2219);
        a2220 = ((a2088)^(Branchtab[82]));
        t418 = (t417 + a2220);
        a2221 = ((a2091)^(Branchtab[114]));
        t419 = (t418 + a2221);
        t420 = (1020 - t419);
        m337 = (X[18] + t419);
        m338 = (X[50] + t420);
        m339 = (X[18] + t420);
        m340 = (X[50] + t419);
        d169 = ((m337 > m338));
        d170 = ((m339 > m340));
        s166 = ((d169) ? (m338) : (m337));
        s167 = ((d170) ? (m340) : (m339));
        a2222 = dec[a2207];
        a2223 = ((d170) << (1));
        a2224 = ((d169)|(a2223));
        a2225 = ((a2224) << (4));
        dec[a2207] = ((a2222)|(a2225));
        Y[36] = s166;
        Y[37] = s167;
        t421 = ((a2083)^(Branchtab[19]));
        a2226 = ((a2085)^(Branchtab[51]));
        t422 = (t421 + a2226);
        a2227 = ((a2088)^(Branchtab[83]));
        t423 = (t422 + a2227);
        a2228 = ((a2091)^(Branchtab[115]));
        t424 = (t423 + a2228);
        t425 = (1020 - t424);
        m341 = (X[19] + t424);
        m342 = (X[51] + t425);
        m343 = (X[19] + t425);
        m344 = (X[51] + t424);
        d171 = ((m341 > m342));
        d172 = ((m343 > m344));
        s168 = ((d171) ? (m342) : (m341));
        s169 = ((d172) ? (m344) : (m343));
        a2229 = dec[a2207];
        a2230 = ((d172) << (1));
        a2231 = ((d171)|(a2230));
        a2232 = ((a2231) << (6));
        dec[a2207] = ((a2229)|(a2232));
        Y[38] = s168;
        Y[39] = s169;
        t426 = ((a2083)^(Branchtab[20]));
        a2233 = ((a2085)^(Branchtab[52]));
        t427 = (t426 + a2233);
        a2234 = ((a2088)^(Branchtab[84]));
        t428 = (t427 + a2234);
        a2235 = ((a2091)^(Branchtab[116]));
        t429 = (t428 + a2235);
        t430 = (1020 - t429);
        m345 = (X[20] + t429);
        m346 = (X[52] + t430);
        m347 = (X[20] + t430);
        m348 = (X[52] + t429);
        d173 = ((m345 > m346));
        d174 = ((m347 > m348));
        s170 = ((d173) ? (m346) : (m345));
        s171 = ((d174) ? (m348) : (m347));
        a2236 = dec[a2207];
        a2237 = ((d174) << (1));
        a2238 = ((d173)|(a2237));
        a2239 = ((a2238) << (8));
        dec[a2207] = ((a2236)|(a2239));
        Y[40] = s170;
        Y[41] = s171;
        t431 = ((a2083)^(Branchtab[21]));
        a2240 = ((a2085)^(Branchtab[53]));
        t432 = (t431 + a2240);
        a2241 = ((a2088)^(Branchtab[85]));
        t433 = (t432 + a2241);
        a2242 = ((a2091)^(Branchtab[117]));
        t434 = (t433 + a2242);
        t435 = (1020 - t434);
        m349 = (X[21] + t434);
        m350 = (X[53] + t435);
        m351 = (X[21] + t435);
        m352 = (X[53] + t434);
        d175 = ((m349 > m350));
        d176 = ((m351 > m352));
        s172 = ((d175) ? (m350) : (m349));
        s173 = ((d176) ? (m352) : (m351));
        a2243 = dec[a2207];
        a2244 = ((d176) << (1));
        a2245 = ((d175)|(a2244));
        a2246 = ((a2245) << (10));
        dec[a2207] = ((a2243)|(a2246));
        Y[42] = s172;
        Y[43] = s173;
        t436 = ((a2083)^(Branchtab[22]));
        a2247 = ((a2085)^(Branchtab[54]));
        t437 = (t436 + a2247);
        a2248 = ((a2088)^(Branchtab[86]));
        t438 = (t437 + a2248);
        a2249 = ((a2091)^(Branchtab[118]));
        t439 = (t438 + a2249);
        t440 = (1020 - t439);
        m353 = (X[22] + t439);
        m354 = (X[54] + t440);
        m355 = (X[22] + t440);
        m356 = (X[54] + t439);
        d177 = ((m353 > m354));
        d178 = ((m355 > m356));
        s174 = ((d177) ? (m354) : (m353));
        s175 = ((d178) ? (m356) : (m355));
        a2250 = dec[a2207];
        a2251 = ((d178) << (1));
        a2252 = ((d177)|(a2251));
        a2253 = ((a2252) << (12));
        dec[a2207] = ((a2250)|(a2253));
        Y[44] = s174;
        Y[45] = s175;
        t441 = ((a2083)^(Branchtab[23]));
        a2254 = ((a2085)^(Branchtab[55]));
        t442 = (t441 + a2254);
        a2255 = ((a2088)^(Branchtab[87]));
        t443 = (t442 + a2255);
        a2256 = ((a2091)^(Branchtab[119]));
        t444 = (t443 + a2256);
        t445 = (1020 - t444);
        m357 = (X[23] + t444);
        m358 = (X[55] + t445);
        m359 = (X[23] + t445);
        m360 = (X[55] + t444);
        d179 = ((m357 > m358));
        d180 = ((m359 > m360));
        s176 = ((d179) ? (m358) : (m357));
        s177 = ((d180) ? (m360) : (m359));
        a2257 = dec[a2207];
        a2258 = ((d180) << (1));
        a2259 = ((d179)|(a2258));
        a2260 = ((a2259) << (14));
        dec[a2207] = ((a2257)|(a2260));
        Y[46] = s176;
        Y[47] = s177;
        t446 = ((a2083)^(Branchtab[24]));
        a2261 = ((a2085)^(Branchtab[56]));
        t447 = (t446 + a2261);
        a2262 = ((a2088)^(Branchtab[88]));
        t448 = (t447 + a2262);
        a2263 = ((a2091)^(Branchtab[120]));
        t449 = (t448 + a2263);
        t450 = (1020 - t449);
        m361 = (X[24] + t449);
        m362 = (X[56] + t450);
        m363 = (X[24] + t450);
        m364 = (X[56] + t449);
        d181 = ((m361 > m362));
        d182 = ((m363 > m364));
        s178 = ((d181) ? (m362) : (m361));
        s179 = ((d182) ? (m364) : (m363));
        a2264 = dec[a2207];
        a2265 = ((d182) << (1));
        a2266 = ((d181)|(a2265));
        a2267 = ((a2266) << (16));
        dec[a2207] = ((a2264)|(a2267));
        Y[48] = s178;
        Y[49] = s179;
        t451 = ((a2083)^(Branchtab[25]));
        a2268 = ((a2085)^(Branchtab[57]));
        t452 = (t451 + a2268);
        a2269 = ((a2088)^(Branchtab[89]));
        t453 = (t452 + a2269);
        a2270 = ((a2091)^(Branchtab[121]));
        t454 = (t453 + a2270);
        t455 = (1020 - t454);
        m365 = (X[25] + t454);
        m366 = (X[57] + t455);
        m367 = (X[25] + t455);
        m368 = (X[57] + t454);
        d183 = ((m365 > m366));
        d184 = ((m367 > m368));
        s180 = ((d183) ? (m366) : (m365));
        s181 = ((d184) ? (m368) : (m367));
        a2271 = dec[a2207];
        a2272 = ((d184) << (1));
        a2273 = ((d183)|(a2272));
        a2274 = ((a2273) << (18));
        dec[a2207] = ((a2271)|(a2274));
        Y[50] = s180;
        Y[51] = s181;
        t456 = ((a2083)^(Branchtab[26]));
        a2275 = ((a2085)^(Branchtab[58]));
        t457 = (t456 + a2275);
        a2276 = ((a2088)^(Branchtab[90]));
        t458 = (t457 + a2276);
        a2277 = ((a2091)^(Branchtab[122]));
        t459 = (t458 + a2277);
        t460 = (1020 - t459);
        m369 = (X[26] + t459);
        m370 = (X[58] + t460);
        m371 = (X[26] + t460);
        m372 = (X[58] + t459);
        d185 = ((m369 > m370));
        d186 = ((m371 > m372));
        s182 = ((d185) ? (m370) : (m369));
        s183 = ((d186) ? (m372) : (m371));
        a2278 = dec[a2207];
        a2279 = ((d186) << (1));
        a2280 = ((d185)|(a2279));
        a2281 = ((a2280) << (20));
        dec[a2207] = ((a2278)|(a2281));
        Y[52] = s182;
        Y[53] = s183;
        t461 = ((a2083)^(Branchtab[27]));
        a2282 = ((a2085)^(Branchtab[59]));
        t462 = (t461 + a2282);
        a2283 = ((a2088)^(Branchtab[91]));
        t463 = (t462 + a2283);
        a2284 = ((a2091)^(Branchtab[123]));
        t464 = (t463 + a2284);
        t465 = (1020 - t464);
        m373 = (X[27] + t464);
        m374 = (X[59] + t465);
        m375 = (X[27] + t465);
        m376 = (X[59] + t464);
        d187 = ((m373 > m374));
        d188 = ((m375 > m376));
        s184 = ((d187) ? (m374) : (m373));
        s185 = ((d188) ? (m376) : (m375));
        a2285 = dec[a2207];
        a2286 = ((d188) << (1));
        a2287 = ((d187)|(a2286));
        a2288 = ((a2287) << (22));
        dec[a2207] = ((a2285)|(a2288));
        Y[54] = s184;
        Y[55] = s185;
        t466 = ((a2083)^(Branchtab[28]));
        a2289 = ((a2085)^(Branchtab[60]));
        t467 = (t466 + a2289);
        a2290 = ((a2088)^(Branchtab[92]));
        t468 = (t467 + a2290);
        a2291 = ((a2091)^(Branchtab[124]));
        t469 = (t468 + a2291);
        t470 = (1020 - t469);
        m377 = (X[28] + t469);
        m378 = (X[60] + t470);
        m379 = (X[28] + t470);
        m380 = (X[60] + t469);
        d189 = ((m377 > m378));
        d190 = ((m379 > m380));
        s186 = ((d189) ? (m378) : (m377));
        s187 = ((d190) ? (m380) : (m379));
        a2292 = dec[a2207];
        a2293 = ((d190) << (1));
        a2294 = ((d189)|(a2293));
        a2295 = ((a2294) << (24));
        dec[a2207] = ((a2292)|(a2295));
        Y[56] = s186;
        Y[57] = s187;
        t471 = ((a2083)^(Branchtab[29]));
        a2296 = ((a2085)^(Branchtab[61]));
        t472 = (t471 + a2296);
        a2297 = ((a2088)^(Branchtab[93]));
        t473 = (t472 + a2297);
        a2298 = ((a2091)^(Branchtab[125]));
        t474 = (t473 + a2298);
        t475 = (1020 - t474);
        m381 = (X[29] + t474);
        m382 = (X[61] + t475);
        m383 = (X[29] + t475);
        m384 = (X[61] + t474);
        d191 = ((m381 > m382));
        d192 = ((m383 > m384));
        s188 = ((d191) ? (m382) : (m381));
        s189 = ((d192) ? (m384) : (m383));
        a2299 = dec[a2207];
        a2300 = ((d192) << (1));
        a2301 = ((d191)|(a2300));
        a2302 = ((a2301) << (26));
        dec[a2207] = ((a2299)|(a2302));
        Y[58] = s188;
        Y[59] = s189;
        t476 = ((a2083)^(Branchtab[30]));
        a2303 = ((a2085)^(Branchtab[62]));
        t477 = (t476 + a2303);
        a2304 = ((a2088)^(Branchtab[94]));
        t478 = (t477 + a2304);
        a2305 = ((a2091)^(Branchtab[126]));
        t479 = (t478 + a2305);
        t480 = (1020 - t479);
        m385 = (X[30] + t479);
        m387 = (X[62] + t480);
        m388 = (X[30] + t480);
        m389 = (X[62] + t479);
        d193 = ((m385 > m387));
        d194 = ((m388 > m389));
        s190 = ((d193) ? (m387) : (m385));
        s191 = ((d194) ? (m389) : (m388));
        a2306 = dec[a2207];
        a2307 = ((d194) << (1));
        a2308 = ((d193)|(a2307));
        a2309 = ((a2308) << (28));
        dec[a2207] = ((a2306)|(a2309));
        Y[60] = s190;
        Y[61] = s191;
        t481 = ((a2083)^(Branchtab[31]));
        a2310 = ((a2085)^(Branchtab[63]));
        t482 = (t481 + a2310);
        a2311 = ((a2088)^(Branchtab[95]));
        t483 = (t482 + a2311);
        a2312 = ((a2091)^(Branchtab[127]));
        t484 = (t483 + a2312);
        t485 = (1020 - t484);
        m390 = (X[31] + t484);
        m391 = (X[63] + t485);
        m392 = (X[31] + t485);
        m393 = (X[63] + t484);
        d195 = ((m390 > m391));
        d196 = ((m392 > m393));
        s192 = ((d195) ? (m391) : (m390));
        s193 = ((d196) ? (m393) : (m392));
        a2313 = dec[a2207];
        a2314 = ((d196) << (1));
        a2315 = ((d195)|(a2314));
        a2316 = ((a2315) << (30));
        dec[a2207] = ((a2313)|(a2316));
        Y[62] = s192;
        Y[63] = s193;
        a2317 = (4 + a2082);
        a2318 = syms[a2317];
        t486 = ((a2318)^(Branchtab[0]));
        a2319 = (5 + a2082);
        a2320 = syms[a2319];
        a2321 = ((a2320)^(Branchtab[32]));
        t487 = (t486 + a2321);
        a2322 = (6 + a2082);
        a2323 = syms[a2322];
        a2324 = ((a2323)^(Branchtab[64]));
        t488 = (t487 + a2324);
        a2325 = (7 + a2082);
        a2326 = syms[a2325];
        a2327 = ((a2326)^(Branchtab[96]));
        t489 = (t488 + a2327);
        t490 = (1020 - t489);
        m394 = (Y[0] + t489);
        m395 = (Y[32] + t490);
        m396 = (Y[0] + t490);
        m397 = (Y[32] + t489);
        d197 = ((m394 > m395));
        d198 = ((m396 > m397));
        s194 = ((d197) ? (m395) : (m394));
        s195 = ((d198) ? (m397) : (m396));
        a2328 = (1 + a2093);
        a2329 = ((a2328) << (1));
        a2330 = dec[a2329];
        a2331 = ((d198) << (1));
        a2332 = ((d197)|(a2331));
        a2333 = ((a2332) << (0));
        dec[a2329] = ((a2330)|(a2333));
        X[0] = s194;
        X[1] = s195;
        t491 = ((a2318)^(Branchtab[1]));
        a2334 = ((a2320)^(Branchtab[33]));
        t492 = (t491 + a2334);
        a2335 = ((a2323)^(Branchtab[65]));
        t493 = (t492 + a2335);
        a2336 = ((a2326)^(Branchtab[97]));
        t494 = (t493 + a2336);
        t495 = (1020 - t494);
        m398 = (Y[1] + t494);
        m399 = (Y[33] + t495);
        m400 = (Y[1] + t495);
        m401 = (Y[33] + t494);
        d199 = ((m398 > m399));
        d200 = ((m400 > m401));
        s196 = ((d199) ? (m399) : (m398));
        s197 = ((d200) ? (m401) : (m400));
        a2337 = dec[a2329];
        a2338 = ((d200) << (1));
        a2339 = ((d199)|(a2338));
        a2340 = ((a2339) << (2));
        dec[a2329] = ((a2337)|(a2340));
        X[2] = s196;
        X[3] = s197;
        t496 = ((a2318)^(Branchtab[2]));
        a2341 = ((a2320)^(Branchtab[34]));
        t497 = (t496 + a2341);
        a2342 = ((a2323)^(Branchtab[66]));
        t498 = (t497 + a2342);
        a2343 = ((a2326)^(Branchtab[98]));
        t499 = (t498 + a2343);
        t500 = (1020 - t499);
        m402 = (Y[2] + t499);
        m403 = (Y[34] + t500);
        m404 = (Y[2] + t500);
        m405 = (Y[34] + t499);
        d201 = ((m402 > m403));
        d202 = ((m404 > m405));
        s198 = ((d201) ? (m403) : (m402));
        s199 = ((d202) ? (m405) : (m404));
        a2344 = dec[a2329];
        a2345 = ((d202) << (1));
        a2346 = ((d201)|(a2345));
        a2347 = ((a2346) << (4));
        dec[a2329] = ((a2344)|(a2347));
        X[4] = s198;
        X[5] = s199;
        t501 = ((a2318)^(Branchtab[3]));
        a2348 = ((a2320)^(Branchtab[35]));
        t502 = (t501 + a2348);
        a2349 = ((a2323)^(Branchtab[67]));
        t503 = (t502 + a2349);
        a2350 = ((a2326)^(Branchtab[99]));
        t504 = (t503 + a2350);
        t505 = (1020 - t504);
        m406 = (Y[3] + t504);
        m407 = (Y[35] + t505);
        m408 = (Y[3] + t505);
        m409 = (Y[35] + t504);
        d203 = ((m406 > m407));
        d204 = ((m408 > m409));
        s200 = ((d203) ? (m407) : (m406));
        s201 = ((d204) ? (m409) : (m408));
        a2351 = dec[a2329];
        a2352 = ((d204) << (1));
        a2353 = ((d203)|(a2352));
        a2354 = ((a2353) << (6));
        dec[a2329] = ((a2351)|(a2354));
        X[6] = s200;
        X[7] = s201;
        t506 = ((a2318)^(Branchtab[4]));
        a2355 = ((a2320)^(Branchtab[36]));
        t507 = (t506 + a2355);
        a2356 = ((a2323)^(Branchtab[68]));
        t508 = (t507 + a2356);
        a2357 = ((a2326)^(Branchtab[100]));
        t509 = (t508 + a2357);
        t510 = (1020 - t509);
        m410 = (Y[4] + t509);
        m411 = (Y[36] + t510);
        m412 = (Y[4] + t510);
        m413 = (Y[36] + t509);
        d205 = ((m410 > m411));
        d206 = ((m412 > m413));
        s202 = ((d205) ? (m411) : (m410));
        s203 = ((d206) ? (m413) : (m412));
        a2358 = dec[a2329];
        a2359 = ((d206) << (1));
        a2360 = ((d205)|(a2359));
        a2361 = ((a2360) << (8));
        dec[a2329] = ((a2358)|(a2361));
        X[8] = s202;
        X[9] = s203;
        t511 = ((a2318)^(Branchtab[5]));
        a2362 = ((a2320)^(Branchtab[37]));
        t512 = (t511 + a2362);
        a2363 = ((a2323)^(Branchtab[69]));
        t513 = (t512 + a2363);
        a2364 = ((a2326)^(Branchtab[101]));
        t514 = (t513 + a2364);
        t515 = (1020 - t514);
        m414 = (Y[5] + t514);
        m415 = (Y[37] + t515);
        m416 = (Y[5] + t515);
        m417 = (Y[37] + t514);
        d207 = ((m414 > m415));
        d208 = ((m416 > m417));
        s204 = ((d207) ? (m415) : (m414));
        s205 = ((d208) ? (m417) : (m416));
        a2365 = dec[a2329];
        a2366 = ((d208) << (1));
        a2367 = ((d207)|(a2366));
        a2368 = ((a2367) << (10));
        dec[a2329] = ((a2365)|(a2368));
        X[10] = s204;
        X[11] = s205;
        t516 = ((a2318)^(Branchtab[6]));
        a2369 = ((a2320)^(Branchtab[38]));
        t517 = (t516 + a2369);
        a2370 = ((a2323)^(Branchtab[70]));
        t518 = (t517 + a2370);
        a2371 = ((a2326)^(Branchtab[102]));
        t519 = (t518 + a2371);
        t520 = (1020 - t519);
        m418 = (Y[6] + t519);
        m419 = (Y[38] + t520);
        m420 = (Y[6] + t520);
        m421 = (Y[38] + t519);
        d209 = ((m418 > m419));
        d210 = ((m420 > m421));
        s206 = ((d209) ? (m419) : (m418));
        s207 = ((d210) ? (m421) : (m420));
        a2372 = dec[a2329];
        a2373 = ((d210) << (1));
        a2374 = ((d209)|(a2373));
        a2375 = ((a2374) << (12));
        dec[a2329] = ((a2372)|(a2375));
        X[12] = s206;
        X[13] = s207;
        t521 = ((a2318)^(Branchtab[7]));
        a2376 = ((a2320)^(Branchtab[39]));
        t522 = (t521 + a2376);
        a2377 = ((a2323)^(Branchtab[71]));
        t523 = (t522 + a2377);
        a2378 = ((a2326)^(Branchtab[103]));
        t524 = (t523 + a2378);
        t525 = (1020 - t524);
        m422 = (Y[7] + t524);
        m423 = (Y[39] + t525);
        m424 = (Y[7] + t525);
        m425 = (Y[39] + t524);
        d211 = ((m422 > m423));
        d212 = ((m424 > m425));
        s208 = ((d211) ? (m423) : (m422));
        s209 = ((d212) ? (m425) : (m424));
        a2379 = dec[a2329];
        a2380 = ((d212) << (1));
        a2381 = ((d211)|(a2380));
        a2382 = ((a2381) << (14));
        dec[a2329] = ((a2379)|(a2382));
        X[14] = s208;
        X[15] = s209;
        t526 = ((a2318)^(Branchtab[8]));
        a2383 = ((a2320)^(Branchtab[40]));
        t527 = (t526 + a2383);
        a2384 = ((a2323)^(Branchtab[72]));
        t528 = (t527 + a2384);
        a2385 = ((a2326)^(Branchtab[104]));
        t529 = (t528 + a2385);
        t530 = (1020 - t529);
        m426 = (Y[8] + t529);
        m427 = (Y[40] + t530);
        m428 = (Y[8] + t530);
        m429 = (Y[40] + t529);
        d213 = ((m426 > m427));
        d214 = ((m428 > m429));
        s210 = ((d213) ? (m427) : (m426));
        s211 = ((d214) ? (m429) : (m428));
        a2386 = dec[a2329];
        a2387 = ((d214) << (1));
        a2388 = ((d213)|(a2387));
        a2389 = ((a2388) << (16));
        dec[a2329] = ((a2386)|(a2389));
        X[16] = s210;
        X[17] = s211;
        t531 = ((a2318)^(Branchtab[9]));
        a2390 = ((a2320)^(Branchtab[41]));
        t532 = (t531 + a2390);
        a2391 = ((a2323)^(Branchtab[73]));
        t533 = (t532 + a2391);
        a2392 = ((a2326)^(Branchtab[105]));
        t534 = (t533 + a2392);
        t535 = (1020 - t534);
        m430 = (Y[9] + t534);
        m431 = (Y[41] + t535);
        m432 = (Y[9] + t535);
        m433 = (Y[41] + t534);
        d215 = ((m430 > m431));
        d216 = ((m432 > m433));
        s212 = ((d215) ? (m431) : (m430));
        s213 = ((d216) ? (m433) : (m432));
        a2393 = dec[a2329];
        a2394 = ((d216) << (1));
        a2395 = ((d215)|(a2394));
        a2396 = ((a2395) << (18));
        dec[a2329] = ((a2393)|(a2396));
        X[18] = s212;
        X[19] = s213;
        t536 = ((a2318)^(Branchtab[10]));
        a2397 = ((a2320)^(Branchtab[42]));
        t537 = (t536 + a2397);
        a2398 = ((a2323)^(Branchtab[74]));
        t538 = (t537 + a2398);
        a2399 = ((a2326)^(Branchtab[106]));
        t539 = (t538 + a2399);
        t540 = (1020 - t539);
        m434 = (Y[10] + t539);
        m435 = (Y[42] + t540);
        m436 = (Y[10] + t540);
        m437 = (Y[42] + t539);
        d217 = ((m434 > m435));
        d218 = ((m436 > m437));
        s214 = ((d217) ? (m435) : (m434));
        s215 = ((d218) ? (m437) : (m436));
        a2400 = dec[a2329];
        a2401 = ((d218) << (1));
        a2402 = ((d217)|(a2401));
        a2403 = ((a2402) << (20));
        dec[a2329] = ((a2400)|(a2403));
        X[20] = s214;
        X[21] = s215;
        t541 = ((a2318)^(Branchtab[11]));
        a2404 = ((a2320)^(Branchtab[43]));
        t542 = (t541 + a2404);
        a2405 = ((a2323)^(Branchtab[75]));
        t543 = (t542 + a2405);
        a2406 = ((a2326)^(Branchtab[107]));
        t544 = (t543 + a2406);
        t545 = (1020 - t544);
        m438 = (Y[11] + t544);
        m439 = (Y[43] + t545);
        m440 = (Y[11] + t545);
        m441 = (Y[43] + t544);
        d219 = ((m438 > m439));
        d220 = ((m440 > m441));
        s216 = ((d219) ? (m439) : (m438));
        s217 = ((d220) ? (m441) : (m440));
        a2407 = dec[a2329];
        a2408 = ((d220) << (1));
        a2409 = ((d219)|(a2408));
        a2410 = ((a2409) << (22));
        dec[a2329] = ((a2407)|(a2410));
        X[22] = s216;
        X[23] = s217;
        t546 = ((a2318)^(Branchtab[12]));
        a2411 = ((a2320)^(Branchtab[44]));
        t547 = (t546 + a2411);
        a2412 = ((a2323)^(Branchtab[76]));
        t548 = (t547 + a2412);
        a2413 = ((a2326)^(Branchtab[108]));
        t549 = (t548 + a2413);
        t550 = (1020 - t549);
        m442 = (Y[12] + t549);
        m443 = (Y[44] + t550);
        m444 = (Y[12] + t550);
        m445 = (Y[44] + t549);
        d221 = ((m442 > m443));
        d222 = ((m444 > m445));
        s218 = ((d221) ? (m443) : (m442));
        s219 = ((d222) ? (m445) : (m444));
        a2414 = dec[a2329];
        a2415 = ((d222) << (1));
        a2416 = ((d221)|(a2415));
        a2417 = ((a2416) << (24));
        dec[a2329] = ((a2414)|(a2417));
        X[24] = s218;
        X[25] = s219;
        t551 = ((a2318)^(Branchtab[13]));
        a2418 = ((a2320)^(Branchtab[45]));
        t552 = (t551 + a2418);
        a2419 = ((a2323)^(Branchtab[77]));
        t553 = (t552 + a2419);
        a2420 = ((a2326)^(Branchtab[109]));
        t554 = (t553 + a2420);
        t555 = (1020 - t554);
        m446 = (Y[13] + t554);
        m447 = (Y[45] + t555);
        m448 = (Y[13] + t555);
        m449 = (Y[45] + t554);
        d223 = ((m446 > m447));
        d224 = ((m448 > m449));
        s220 = ((d223) ? (m447) : (m446));
        s221 = ((d224) ? (m449) : (m448));
        a2421 = dec[a2329];
        a2422 = ((d224) << (1));
        a2423 = ((d223)|(a2422));
        a2424 = ((a2423) << (26));
        dec[a2329] = ((a2421)|(a2424));
        X[26] = s220;
        X[27] = s221;
        t556 = ((a2318)^(Branchtab[14]));
        a2425 = ((a2320)^(Branchtab[46]));
        t557 = (t556 + a2425);
        a2426 = ((a2323)^(Branchtab[78]));
        t558 = (t557 + a2426);
        a2427 = ((a2326)^(Branchtab[110]));
        t559 = (t558 + a2427);
        t560 = (1020 - t559);
        m450 = (Y[14] + t559);
        m451 = (Y[46] + t560);
        m452 = (Y[14] + t560);
        m453 = (Y[46] + t559);
        d225 = ((m450 > m451));
        d226 = ((m452 > m453));
        s222 = ((d225) ? (m451) : (m450));
        s223 = ((d226) ? (m453) : (m452));
        a2428 = dec[a2329];
        a2429 = ((d226) << (1));
        a2430 = ((d225)|(a2429));
        a2431 = ((a2430) << (28));
        dec[a2329] = ((a2428)|(a2431));
        X[28] = s222;
        X[29] = s223;
        t561 = ((a2318)^(Branchtab[15]));
        a2432 = ((a2320)^(Branchtab[47]));
        t562 = (t561 + a2432);
        a2433 = ((a2323)^(Branchtab[79]));
        t563 = (t562 + a2433);
        a2434 = ((a2326)^(Branchtab[111]));
        t564 = (t563 + a2434);
        t565 = (1020 - t564);
        m454 = (Y[15] + t564);
        m455 = (Y[47] + t565);
        m456 = (Y[15] + t565);
        m457 = (Y[47] + t564);
        d227 = ((m454 > m455));
        d228 = ((m456 > m457));
        s224 = ((d227) ? (m455) : (m454));
        s225 = ((d228) ? (m457) : (m456));
        a2435 = dec[a2329];
        a2436 = ((d228) << (1));
        a2437 = ((d227)|(a2436));
        a2438 = ((a2437) << (30));
        dec[a2329] = ((a2435)|(a2438));
        X[30] = s224;
        X[31] = s225;
        t566 = ((a2318)^(Branchtab[16]));
        a2439 = ((a2320)^(Branchtab[48]));
        t567 = (t566 + a2439);
        a2440 = ((a2323)^(Branchtab[80]));
        t568 = (t567 + a2440);
        a2441 = ((a2326)^(Branchtab[112]));
        t569 = (t568 + a2441);
        t570 = (1020 - t569);
        m458 = (Y[16] + t569);
        m459 = (Y[48] + t570);
        m460 = (Y[16] + t570);
        m461 = (Y[48] + t569);
        d229 = ((m458 > m459));
        d230 = ((m460 > m461));
        s226 = ((d229) ? (m459) : (m458));
        s227 = ((d230) ? (m461) : (m460));
        a2442 = (1 + a2329);
        a2443 = dec[a2442];
        a2444 = ((d230) << (1));
        a2445 = ((d229)|(a2444));
        a2446 = ((a2445) << (0));
        dec[a2442] = ((a2443)|(a2446));
        X[32] = s226;
        X[33] = s227;
        t571 = ((a2318)^(Branchtab[17]));
        a2447 = ((a2320)^(Branchtab[49]));
        t572 = (t571 + a2447);
        a2448 = ((a2323)^(Branchtab[81]));
        t573 = (t572 + a2448);
        a2449 = ((a2326)^(Branchtab[113]));
        t574 = (t573 + a2449);
        t575 = (1020 - t574);
        m462 = (Y[17] + t574);
        m463 = (Y[49] + t575);
        m464 = (Y[17] + t575);
        m465 = (Y[49] + t574);
        d231 = ((m462 > m463));
        d232 = ((m464 > m465));
        s228 = ((d231) ? (m463) : (m462));
        s229 = ((d232) ? (m465) : (m464));
        a2450 = dec[a2442];
        a2451 = ((d232) << (1));
        a2452 = ((d231)|(a2451));
        a2453 = ((a2452) << (2));
        dec[a2442] = ((a2450)|(a2453));
        X[34] = s228;
        X[35] = s229;
        t576 = ((a2318)^(Branchtab[18]));
        a2454 = ((a2320)^(Branchtab[50]));
        t577 = (t576 + a2454);
        a2455 = ((a2323)^(Branchtab[82]));
        t578 = (t577 + a2455);
        a2456 = ((a2326)^(Branchtab[114]));
        t579 = (t578 + a2456);
        t580 = (1020 - t579);
        m466 = (Y[18] + t579);
        m467 = (Y[50] + t580);
        m468 = (Y[18] + t580);
        m469 = (Y[50] + t579);
        d233 = ((m466 > m467));
        d234 = ((m468 > m469));
        s230 = ((d233) ? (m467) : (m466));
        s231 = ((d234) ? (m469) : (m468));
        a2457 = dec[a2442];
        a2458 = ((d234) << (1));
        a2459 = ((d233)|(a2458));
        a2460 = ((a2459) << (4));
        dec[a2442] = ((a2457)|(a2460));
        X[36] = s230;
        X[37] = s231;
        t581 = ((a2318)^(Branchtab[19]));
        a2461 = ((a2320)^(Branchtab[51]));
        t582 = (t581 + a2461);
        a2462 = ((a2323)^(Branchtab[83]));
        t583 = (t582 + a2462);
        a2463 = ((a2326)^(Branchtab[115]));
        t584 = (t583 + a2463);
        t585 = (1020 - t584);
        m470 = (Y[19] + t584);
        m471 = (Y[51] + t585);
        m472 = (Y[19] + t585);
        m473 = (Y[51] + t584);
        d235 = ((m470 > m471));
        d236 = ((m472 > m473));
        s232 = ((d235) ? (m471) : (m470));
        s233 = ((d236) ? (m473) : (m472));
        a2464 = dec[a2442];
        a2465 = ((d236) << (1));
        a2466 = ((d235)|(a2465));
        a2467 = ((a2466) << (6));
        dec[a2442] = ((a2464)|(a2467));
        X[38] = s232;
        X[39] = s233;
        t586 = ((a2318)^(Branchtab[20]));
        a2468 = ((a2320)^(Branchtab[52]));
        t587 = (t586 + a2468);
        a2469 = ((a2323)^(Branchtab[84]));
        t588 = (t587 + a2469);
        a2470 = ((a2326)^(Branchtab[116]));
        t589 = (t588 + a2470);
        t590 = (1020 - t589);
        m474 = (Y[20] + t589);
        m475 = (Y[52] + t590);
        m476 = (Y[20] + t590);
        m477 = (Y[52] + t589);
        d237 = ((m474 > m475));
        d238 = ((m476 > m477));
        s234 = ((d237) ? (m475) : (m474));
        s235 = ((d238) ? (m477) : (m476));
        a2471 = dec[a2442];
        a2472 = ((d238) << (1));
        a2473 = ((d237)|(a2472));
        a2474 = ((a2473) << (8));
        dec[a2442] = ((a2471)|(a2474));
        X[40] = s234;
        X[41] = s235;
        t591 = ((a2318)^(Branchtab[21]));
        a2475 = ((a2320)^(Branchtab[53]));
        t592 = (t591 + a2475);
        a2476 = ((a2323)^(Branchtab[85]));
        t593 = (t592 + a2476);
        a2477 = ((a2326)^(Branchtab[117]));
        t594 = (t593 + a2477);
        t595 = (1020 - t594);
        m478 = (Y[21] + t594);
        m479 = (Y[53] + t595);
        m480 = (Y[21] + t595);
        m481 = (Y[53] + t594);
        d239 = ((m478 > m479));
        d240 = ((m480 > m481));
        s236 = ((d239) ? (m479) : (m478));
        s237 = ((d240) ? (m481) : (m480));
        a2478 = dec[a2442];
        a2479 = ((d240) << (1));
        a2480 = ((d239)|(a2479));
        a2481 = ((a2480) << (10));
        dec[a2442] = ((a2478)|(a2481));
        X[42] = s236;
        X[43] = s237;
        t596 = ((a2318)^(Branchtab[22]));
        a2482 = ((a2320)^(Branchtab[54]));
        t597 = (t596 + a2482);
        a2483 = ((a2323)^(Branchtab[86]));
        t598 = (t597 + a2483);
        a2484 = ((a2326)^(Branchtab[118]));
        t599 = (t598 + a2484);
        t600 = (1020 - t599);
        m482 = (Y[22] + t599);
        m483 = (Y[54] + t600);
        m484 = (Y[22] + t600);
        m485 = (Y[54] + t599);
        d241 = ((m482 > m483));
        d242 = ((m484 > m485));
        s238 = ((d241) ? (m483) : (m482));
        s239 = ((d242) ? (m485) : (m484));
        a2485 = dec[a2442];
        a2486 = ((d242) << (1));
        a2487 = ((d241)|(a2486));
        a2488 = ((a2487) << (12));
        dec[a2442] = ((a2485)|(a2488));
        X[44] = s238;
        X[45] = s239;
        t601 = ((a2318)^(Branchtab[23]));
        a2489 = ((a2320)^(Branchtab[55]));
        t602 = (t601 + a2489);
        a2490 = ((a2323)^(Branchtab[87]));
        t603 = (t602 + a2490);
        a2491 = ((a2326)^(Branchtab[119]));
        t604 = (t603 + a2491);
        t605 = (1020 - t604);
        m486 = (Y[23] + t604);
        m487 = (Y[55] + t605);
        m488 = (Y[23] + t605);
        m489 = (Y[55] + t604);
        d243 = ((m486 > m487));
        d244 = ((m488 > m489));
        s240 = ((d243) ? (m487) : (m486));
        s241 = ((d244) ? (m489) : (m488));
        a2492 = dec[a2442];
        a2493 = ((d244) << (1));
        a2494 = ((d243)|(a2493));
        a2495 = ((a2494) << (14));
        dec[a2442] = ((a2492)|(a2495));
        X[46] = s240;
        X[47] = s241;
        t606 = ((a2318)^(Branchtab[24]));
        a2496 = ((a2320)^(Branchtab[56]));
        t607 = (t606 + a2496);
        a2497 = ((a2323)^(Branchtab[88]));
        t608 = (t607 + a2497);
        a2498 = ((a2326)^(Branchtab[120]));
        t609 = (t608 + a2498);
        t610 = (1020 - t609);
        m490 = (Y[24] + t609);
        m491 = (Y[56] + t610);
        m492 = (Y[24] + t610);
        m493 = (Y[56] + t609);
        d245 = ((m490 > m491));
        d246 = ((m492 > m493));
        s242 = ((d245) ? (m491) : (m490));
        s243 = ((d246) ? (m493) : (m492));
        a2499 = dec[a2442];
        a2500 = ((d246) << (1));
        a2501 = ((d245)|(a2500));
        a2502 = ((a2501) << (16));
        dec[a2442] = ((a2499)|(a2502));
        X[48] = s242;
        X[49] = s243;
        t611 = ((a2318)^(Branchtab[25]));
        a2503 = ((a2320)^(Branchtab[57]));
        t612 = (t611 + a2503);
        a2504 = ((a2323)^(Branchtab[89]));
        t613 = (t612 + a2504);
        a2505 = ((a2326)^(Branchtab[121]));
        t614 = (t613 + a2505);
        t615 = (1020 - t614);
        m494 = (Y[25] + t614);
        m495 = (Y[57] + t615);
        m496 = (Y[25] + t615);
        m497 = (Y[57] + t614);
        d247 = ((m494 > m495));
        d248 = ((m496 > m497));
        s244 = ((d247) ? (m495) : (m494));
        s245 = ((d248) ? (m497) : (m496));
        a2506 = dec[a2442];
        a2507 = ((d248) << (1));
        a2508 = ((d247)|(a2507));
        a2509 = ((a2508) << (18));
        dec[a2442] = ((a2506)|(a2509));
        X[50] = s244;
        X[51] = s245;
        t616 = ((a2318)^(Branchtab[26]));
        a2510 = ((a2320)^(Branchtab[58]));
        t617 = (t616 + a2510);
        a2511 = ((a2323)^(Branchtab[90]));
        t618 = (t617 + a2511);
        a2512 = ((a2326)^(Branchtab[122]));
        t619 = (t618 + a2512);
        t620 = (1020 - t619);
        m498 = (Y[26] + t619);
        m499 = (Y[58] + t620);
        m500 = (Y[26] + t620);
        m501 = (Y[58] + t619);
        d249 = ((m498 > m499));
        d250 = ((m500 > m501));
        s246 = ((d249) ? (m499) : (m498));
        s247 = ((d250) ? (m501) : (m500));
        a2513 = dec[a2442];
        a2514 = ((d250) << (1));
        a2515 = ((d249)|(a2514));
        a2516 = ((a2515) << (20));
        dec[a2442] = ((a2513)|(a2516));
        X[52] = s246;
        X[53] = s247;
        t621 = ((a2318)^(Branchtab[27]));
        a2517 = ((a2320)^(Branchtab[59]));
        t622 = (t621 + a2517);
        a2518 = ((a2323)^(Branchtab[91]));
        t623 = (t622 + a2518);
        a2519 = ((a2326)^(Branchtab[123]));
        t624 = (t623 + a2519);
        t625 = (1020 - t624);
        m502 = (Y[27] + t624);
        m503 = (Y[59] + t625);
        m504 = (Y[27] + t625);
        m505 = (Y[59] + t624);
        d251 = ((m502 > m503));
        d252 = ((m504 > m505));
        s248 = ((d251) ? (m503) : (m502));
        s249 = ((d252) ? (m505) : (m504));
        a2520 = dec[a2442];
        a2521 = ((d252) << (1));
        a2522 = ((d251)|(a2521));
        a2523 = ((a2522) << (22));
        dec[a2442] = ((a2520)|(a2523));
        X[54] = s248;
        X[55] = s249;
        t626 = ((a2318)^(Branchtab[28]));
        a2524 = ((a2320)^(Branchtab[60]));
        t627 = (t626 + a2524);
        a2525 = ((a2323)^(Branchtab[92]));
        t628 = (t627 + a2525);
        a2526 = ((a2326)^(Branchtab[124]));
        t629 = (t628 + a2526);
        t630 = (1020 - t629);
        m506 = (Y[28] + t629);
        m507 = (Y[60] + t630);
        m508 = (Y[28] + t630);
        m509 = (Y[60] + t629);
        d253 = ((m506 > m507));
        d254 = ((m508 > m509));
        s250 = ((d253) ? (m507) : (m506));
        s251 = ((d254) ? (m509) : (m508));
        a2527 = dec[a2442];
        a2528 = ((d254) << (1));
        a2529 = ((d253)|(a2528));
        a2530 = ((a2529) << (24));
        dec[a2442] = ((a2527)|(a2530));
        X[56] = s250;
        X[57] = s251;
        t631 = ((a2318)^(Branchtab[29]));
        a2531 = ((a2320)^(Branchtab[61]));
        t632 = (t631 + a2531);
        a2532 = ((a2323)^(Branchtab[93]));
        t633 = (t632 + a2532);
        a2533 = ((a2326)^(Branchtab[125]));
        t634 = (t633 + a2533);
        t635 = (1020 - t634);
        m510 = (Y[29] + t634);
        m511 = (Y[61] + t635);
        m512 = (Y[29] + t635);
        m513 = (Y[61] + t634);
        d255 = ((m510 > m511));
        d256 = ((m512 > m513));
        s252 = ((d255) ? (m511) : (m510));
        s253 = ((d256) ? (m513) : (m512));
        a2534 = dec[a2442];
        a2535 = ((d256) << (1));
        a2536 = ((d255)|(a2535));
        a2537 = ((a2536) << (26));
        dec[a2442] = ((a2534)|(a2537));
        X[58] = s252;
        X[59] = s253;
        t636 = ((a2318)^(Branchtab[30]));
        a2538 = ((a2320)^(Branchtab[62]));
        t637 = (t636 + a2538);
        a2539 = ((a2323)^(Branchtab[94]));
        t638 = (t637 + a2539);
        a2540 = ((a2326)^(Branchtab[126]));
        t639 = (t638 + a2540);
        t640 = (1020 - t639);
        m514 = (Y[30] + t639);
        m515 = (Y[62] + t640);
        m516 = (Y[30] + t640);
        m517 = (Y[62] + t639);
        d257 = ((m514 > m515));
        d258 = ((m516 > m517));
        s254 = ((d257) ? (m515) : (m514));
        s255 = ((d258) ? (m517) : (m516));
        a2541 = dec[a2442];
        a2542 = ((d258) << (1));
        a2543 = ((d257)|(a2542));
        a2544 = ((a2543) << (28));
        dec[a2442] = ((a2541)|(a2544));
        X[60] = s254;
        X[61] = s255;
        t641 = ((a2318)^(Branchtab[31]));
        a2545 = ((a2320)^(Branchtab[63]));
        t642 = (t641 + a2545);
        a2546 = ((a2323)^(Branchtab[95]));
        t643 = (t642 + a2546);
        a2547 = ((a2326)^(Branchtab[127]));
        t644 = (t643 + a2547);
        t645 = (1020 - t644);
        m518 = (Y[31] + t644);
        m519 = (Y[63] + t645);
        m520 = (Y[31] + t645);
        m521 = (Y[63] + t644);
        d259 = ((m518 > m519));
        d260 = ((m520 > m521));
        s256 = ((d259) ? (m519) : (m518));
        s257 = ((d260) ? (m521) : (m520));
        a2548 = dec[a2442];
        a2549 = ((d260) << (1));
        a2550 = ((d259)|(a2549));
        a2551 = ((a2550) << (30));
        dec[a2442] = ((a2548)|(a2551));
        X[62] = s256;
        X[63] = s257;
    }
    /* skip */
}
#endif

