name: Linux build

on:
  push:
    branches:
      - master
      - next
      - 'next*'
    tags:
      - 'v*'

jobs:
  qtbuild:
    name: Build with Qt
    runs-on: ubuntu-22.04

    steps:
      - name: Install Qt
        uses: jurplel/install-qt-action@v4
        with:
          version: '6.7.2'
      - name: Checkout
        uses: actions/checkout@v3

      - run: git fetch --prune --unshallow --tags

      - name: Set environment variables
        run: |
          echo "DATE=`date +%Y%m%d`" >> $GITHUB_ENV
          echo "GIT_HASH=`git rev-parse --short HEAD`" >> $GITHUB_ENV
          cat $GITHUB_ENV

      - name: Display environment variables
        run: env | sort

      - name: Install build dependencies
        run: |
            set -x
            sudo apt-get -y install build-essential libfaad-dev libmpg123-dev libfftw3-dev librtlsdr-dev libusb-1.0-0-dev mesa-common-dev libglu1-mesa-dev libpulse-dev libsoapysdr-dev libairspy-dev libmp3lame-dev libflac++-dev
     
      - name: Build
        id: build
        run: |
            mkdir build
            cd build
            qmake PREFIX=/usr ..
            make
            cd ..
            echo $PWD

      - name: Archive artifacts (welle.io build dir)
        if: always() && steps.build.outcome == 'failure'
        uses: actions/upload-artifact@v3
        with:
          name: welle.io build dir
          path: build/*
          if-no-files-found: error
