name: Raspberry Pi build

on:
  push:
    branches:
      - master
      - next
      - 'next*'

jobs:
  buildx:
    name: Build with Buildx
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - run: git fetch --prune --unshallow --tags

      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
        with:
          platforms: arm

      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          platforms: linux/arm/v6

      -
        name: Build
        id: build
        run: |
          mkdir build/
          docker build -f Dockerfile.raspberrypi --platform linux/arm/v6 --target export -t build --output . .
          ls -lah

      - name: Archive artifacts (welle.io build dir)
        if: always() && steps.build.outcome == 'failure'
        uses: actions/upload-artifact@v4
        with:
          name: welle.io build dir
          path: build/*
          if-no-files-found: error
