name: Windows build

on:
  push:
    branches:
      - master
      - next
      - 'next*'
    tags:
      - 'v*'

jobs:
  qtbuild:
    name: Build with Qt
    runs-on: windows-latest

    steps:
      - name: Install Qt
        uses: jurplel/install-qt-action@v4
        with:
          version: '6.7.2'
          modules: 'qtcharts qtmultimedia'
          arch: 'win64_mingw'
      - name: Checkout
        uses: actions/checkout@v3

      - run: git fetch --prune --unshallow --tags
        
      - name: Preapre build
        shell: cmd
        run: |
            echo Create datetime
            for /f "tokens=2 delims==" %%G in ('wmic os get localdatetime /value') do set datetime=%%G
            set year=%datetime:~0,4%
            set month=%datetime:~4,2%
            set day=%datetime:~6,2%
            echo current_date=%year%%month%%day% >> $GITHUB_ENV
            
            echo Create git hash
            for /f %%i in ('git -C %GITHUB_WORKSPACE% rev-parse --short HEAD') do set git_hash=%%i
            echo git_hash=%git_hash% >> $GITHUB_ENV
            
            echo Create version
            echo file_version=%current_date%_%git_hash% >> $GITHUB_ENV
            
            echo Create a build directory
            cd ..\
            md build
            
            REM Get all headers and DLLs for the build
            git clone https://github.com/AlbrechtL/welle.io-win-libs.git

      - name: Display environment variables
        run: | 
          Get-ChildItem Env:
     
      - name: Build
        id: build
        shell: cmd
        run: |
            cd build
            qmake ..\welle-io
            mingw32-make
        
      - name: Archive artifacts (welle.io build dir)
        if: always() && steps.build.outcome == 'failure'
        uses: actions/upload-artifact@v3
        with:
          name: welle.io build dir
          path: build/*
          if-no-files-found: error
