name: Windows build

on:
  push:
    branches:
      - master
      - next
      - 'next*'
    tags:
      - 'v*'

jobs:
  qtbuild:
    name: Build with Qt
    runs-on: windows-latest

    steps:
      - name: Install Qt
        uses: jurplel/install-qt-action@v4
        with:
          version: '6.7.2'
          modules: 'qtcharts qtmultimedia'
          arch: 'win64_mingw'
      - name: Checkout
        uses: actions/checkout@v3

      - run: git fetch --prune --unshallow --tags
        
      - name: Preapre build
        run: |
            echo Create datetime
            $current_date=$(Get-Date -Format 'yyyyMMdd')
            "current_date=$current_date" >> $env:GITHUB_ENV
            
            echo Create git hash
            git_hash=$(git -C . rev-parse --short HEAD)
            "git_hash=$git_hash" >> $env:GITHUB_ENV
            
            echo Create version
            $file_version=$current_date_$git_hash
            "file_version=$file_version" >> $$env:GITHUB_ENV
            
            echo Create a build directory
            cd ..\
            md build
            
            REM Get all headers and DLLs for the build
            git clone https://github.com/AlbrechtL/welle.io-win-libs.git

      - name: Display environment variables
        run: | 
          Get-ChildItem Env:
     
      - name: Build
        id: build
        shell: cmd
        run: |
            cd build
            qmake ..\welle-io
            mingw32-make
        
      - name: Archive artifacts (welle.io build dir)
        if: always() && steps.build.outcome == 'failure'
        uses: actions/upload-artifact@v3
        with:
          name: welle.io build dir
          path: build/*
          if-no-files-found: error
