name: Windows build

on:
  push:
    branches:
      - master
      - next
      - 'next*'
    tags:
      - 'v*'

jobs:
  qtbuild:
    name: Build with Qt
    runs-on: windows-latest

    steps:
      - name: Install Qt
        uses: jurplel/install-qt-action@v4
        with:
          version: '6.7.2'
          modules: 'qtcharts qtmultimedia qt5compat qtshadertools'
          arch: 'win64_mingw'
          tools: 'tools_mingw90'
      - name: Checkout
        uses: actions/checkout@v4

      - run: git fetch --prune --unshallow --tags
        
      - name: Preapre build
        run: |            
            echo "Create a build directory"
            md build
            cd build
            md release
            
            echo "Get all headers and DLLs for the build"
            cd ../..
            git clone https://github.com/AlbrechtL/welle.io-win-libs.git

      - name: Display environment variables
        run: | 
          Get-ChildItem Env:
     
      - name: Build
        id: build
        run: |
            cd build/release
            qmake ../..
            mingw32-make -j4

      - name: Create installer
        id: create_installer
        run: |
            Write-Host "*** Create new bin folder ***" -ForegroundColor Red
            New-Item -ItemType directory -Path installer
            
            Write-Host "*** Copy non QT DLLs from welle.io-win-libs repository ***" -ForegroundColor Red
            Copy-Item ..\welle.io-win-libs\x64\*.dll installer  -recurse
            
            Write-Host "*** Copy welle-io binary files ***" -ForegroundColor Red
            Copy-Item build\release\src\welle-gui\release\welle-io.exe installer
            
            # Deploy QT and related plugins
            Write-Host "*** Deploy QT and related plugins ***" -ForegroundColor Red
            & windeployqt installer\welle-io.exe --qmldir src\welle-gui\QML\ --no-translations

            echo "Create filename"
            $current_date=$(Get-Date -Format 'yyyyMMdd')
            $git_hash=$(git -C . rev-parse --short HEAD)
            $Filename = $current_date + "_" + $git_hash + "_Windows_welle-io-setup_x64"

            # Run InnoSetup
            & ISCC /O.\ /F$Filename windows/installer.iss

      - name: Archive artifacts (welle.io Windows installer)
        if: always() && steps.create_installer.outcome == 'success'
        uses: actions/upload-artifact@v4
        with:
          name: welle.io Windows installer
          path: .\*.exe
          if-no-files-found: error
